### ISSUE TITLE
It needs to be possible to rename a go_binary rule

### ISSUE THREAD

**Issue by ianthehat** [bazelbuild/bazel-gazelle#106]
At the moment gazelle does not work correctly with go_binary rules that are not the same name as the folder.
While that should be the default when generating new rules, if there is an existing go_binary rule then gazelle should probably presume it is maintaining that one rather than adding a new one. If there is more than one, it should probably just give up and print a warning?

**Comment by jmmv** [comment]
This is a dup of the bug I already filed: https://github.com/bazelbuild/bazel-gazelle/issues/99

I'd suggest to go with the simple approach first of just recognizing/respecting a single target so that we can mitigate the problems introduced by https://github.com/bazelbuild/rules_go/issues/1239.

A more flexible matching algorithm would be great, but I feel it can come later. An idea might be to match based on source files? (Of course that doesn't let you recognize and automatically add new files to existing rules, but might be sufficient?)

**Comment by jayconrod** [comment]
This is a little different than #99. This is asking for Gazelle to match go_binary rules with customized names without any explicit annotation. It addresses the same problem as #99 though, so I think when #108 is merged, both issues can be closed.

In terms of implementation difficulty, I think matching source files would be harder to get right in general. Let's go with #108 first, and if it seems like there's still a strong case for source file matching, we can figure out how to proceed.

**Comment by jmmv** [comment]
#99 asked for a mechanism to keep custom binary names. The proposal for an annotation was just a possible way of implementing that, but of course not the only one.
