### ISSUE TITLE
Added explicit grpc-go dependency breaks users

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/bazel-gazelle#1115]
### What version of gazelle are you using?

`v0.24.0`

### What version of rules_go are you using?

`v0.25.1`

### What version of Bazel are you using?

`v3.5.0`

### Does this issue reproduce with the latest releases of all the above?

Yes (I understand I need to update `rules_go` for this version to work at all, but it's still broken at the latest version).

### What operating system and processor architecture are you using?

Linux/amd64

### What did you do?

I tried updating to `v0.24.0` in a repository that has an existing `grpc-go` dependency (https://github.com/grpc-ecosystem/grpc-gateway/pull/2382) AND checked in generated protobuf files.

### What did you expect to see?

I expected my project to continue building successfully.

### What did you see instead?

I am seeing a build error: `undefined: grpc.SupportPackageIsVersion7`. (See CI logs in aforementioned PR for more details).

### Discussion

I'm ignorant to some of the steps happening here, but I know that the build error in question is encountered if using a version of the `grpc` runtime library < `v1.32.0` (See https://github.com/grpc/grpc-go/releases/tag/v1.32.0 and more specifically https://github.com/grpc/grpc-go/pull/3818). I went through the commit history and noticed that `v0.24.0` added an explicit dependency on `grpc-go` at `v1.27.0` (See https://github.com/bazelbuild/bazel-gazelle/pull/1111). I can only imagine the build error has something to do with this, but I don't understand the whole build system well enough to say for sure.

I thought I might be able to fix this by importing our locally defined grpc runtime library version (in `repositories.bzl`) after `go_rules_dependencies()`, but that didn't change anything.

I'm curious why such an old gRPC version was pinned. `v1.27.0` was released in January of 2020: https://github.com/grpc/grpc-go/releases/tag/v1.27.0.

**Comment by robfig** [comment]
Gazelle does not depend directly on gRPC, so that version would have been calculated based on MVS, which can select older versions for stability rather than defaulting to the latest version. 

To override, just declare your desired version of gRPC as a `go_repository`, prior to calling `gazelle_dependencies()`. This isn't described in the Gazelle repo afaik, but it's the same process as in rules_go: https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies

Let me know if that doesn't solve your problem.

**Comment by johanbrandhorst** [comment]
Ah, I did read that link, but didn't realize I needed to call `gazelle_dependencies()` instead of `go_rules_dependencies()`. I have a `go_repository` defined: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/repositories.bzl#L1075-L1080. Moving the `gazelle_dependencies()` after `go_repositories()` does appear to have fixed the build, thanks a lot! I don't know if this issue can be closed or if it'd be good to have it open and discuss the unintended consequence of the dependency addition?

I'm a little confused as to how this resolution happens.Why does the order in which I call things in `WORKSPACE` matter? Shouldn't it take both versions into account?

Separetely, why is Gazelle depending on gRPC at all? To the extent that it's overriding the version explicitly specified in my `repositories.bzl`?

**Comment by robfig** [comment]
Each external repository can only point to a single set of source code. If you declare the same external repository multiple times, I believe the first one wins, although bazel query will incorrectly report that you are using the last one. (I've been meaning to file that as an issue upstream.) For better or worse, rules_go and gazelle use the same external repository names that Gazelle generates, so they use a macro (search for `_maybe`) which only declares it if the repository is not already defined. This works fine as long as callers define their own desired dependencies first, but it can be confusing when that's not the case. 

TBH, I'm not sure if there's anything stopping rules_go and gazelle from using external repository names which would not conflict with Gazelle. The downside is that you would download and build multiple copies of those libraries, but that might be a good tradeoff with avoidance of confusing errors. Any color to add @jayconrod ?

**Comment by v3n** [comment]
Why was this closed? I see several issues here:

Several dependencies were added to gazelle without any mention of them in the patch notes, which was a breaking change given the suggested load order in the README. This broken a number of dependencies for us, especially dependencies that I don't understand why Gazelle even depends on.

Secondly, It's one thing to add dependencies, it's another to force dependencies dependencies that are _multiple years out of date_. If this hadn't broken my build in multiple ways, I would have no idea that this caused an almost 2-year regression of bug and security fixes.
  - pgv -> 0.1.0 (Jun 2019)
  - grpc -> 0.27.0 (Jan 2020)

> Separately, why is Gazelle depending on gRPC at all?

This was unanswered.

> although bazel query will incorrectly report that you are using the last one. (I've been meaning to file that as an issue upstream.)

https://github.com/bazelbuild/bazel/issues/12947

**Comment by robfig** [comment]
> Several dependencies were added to gazelle without any mention of them in the patch notes, which was a breaking change given the suggested load order in the README. This broken a number of dependencies for us, especially dependencies that I don't understand why Gazelle even depends on.

You're right, we should have mentioned the new dependencies in the release notes. 

I agree that this should be better documented, and we should recommend that users declare all of their dependencies prior to loading gazelle or rules_go dependencies. The relevant documentation is present at https://github.com/bazelbuild/rules_go/#protobuf-and-grpc , linking to https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies.

> Secondly, It's one thing to add dependencies, it's another to force dependencies that are multiple years out of date. If this hadn't broken my build in multiple ways, I would have no idea that this caused an almost 2-year regression of bug and security fixes.

Anyone who overrides dependencies as described by the link above would continue to use those versions, so I don't really agree with the characterization of "force". That the first declaration of the repository "wins" is how Bazel works.

>> Separately, why is Gazelle depending on gRPC at all?
> This was unanswered.

grpc is used by rules_go to support its proto rules, since it can generate grpc service definitions. Gazelle depends on rules_go, and the referenced PR pulled in its transitive dependencies. You can see the process that was followed here:
https://github.com/bazelbuild/bazel-gazelle/wiki/Release-process

I do see this comment about avoiding the dependency in `@rules_go//go/private/repositories.bzl`:

```
    # Proto dependencies
    # These are limited as much as possible. In most cases, users need to
    # declare these on their own (probably via go_repository rules generated
    # with 'gazelle update-repos -from_file=go.mod). There are several
    # reasons for this:
    #
    # * com_google_protobuf has its own dependency macro. We can't load
    #   the macro here.
    # * rules_proto also has a dependency macro. It's only needed by tests and
    #   by gogo_special_proto. Users will need to declare it anyway.
    # * org_golang_google_grpc has too many dependencies for us to maintain.
    # * In general, declaring dependencies here confuses users when they
    #   declare their own dependencies later. Bazel ignores these.
    # * Most proto repos are updated more frequently than rules_go, and
    #   we can't keep up.
```

I suppose that behavior was not maintained in the Gazelle dependencies, when it should have been.

> bazelbuild/bazel#12947

Thanks for the link, commented to add support.

====

It sounds like this issue should have the following fixes:

* Update boilerplate / documentation to clearly identify that go_repository dependencies should be loaded prior to rules_go and gazelle dependencies
* Screen out the grpc dependency in gazelle as is done in rules_go

Thanks

**Comment by v3n** [comment]
Thanks for the responsiveness and apologies for coming on strong. Appreciate everything y'all do.

> I agree that this should be better documented, and we should recommend that users declare all of their dependencies prior to loading gazelle or rules_go dependencies.

This would be a great recommendation. To be honestly, I didn't even know that I could load my dependencies before any of the rules_go/gazelle dependencies--I assumed that those were needed to make go_repository work. This would definitely be our preferred approach--it means that the go.mod file is actually the source of truth.

**Comment by robfig** [comment]
There didn't seem to be any reasonable way to screen out specific dependencies, so instead I updated the boilerplate on README and added a large section to the v0.24 release notes. I think that should mitigate the problem without making the maintainers have to start managing gazelle deps by hand. Thanks for the report and apologies for the hassle!
