### ISSUE TITLE
Regenerate external BUILD when gazelle:proto disable

### ISSUE THREAD

**Issue by wenerme** [bazelbuild/bazel-gazelle#1149]
### What version of gazelle are you using?

v0.24.0

### What version of rules_go are you using?

v0.29.0

### What version of Bazel are you using?

4.22

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

macos

### What did you do?

When work with https://github.com/asim/go-micro/tree/master/debug/proto

```
external/dev_go_micro_v4/debug/proto/debug.pb.micro.go:4:9: package debug; expected proto
```

enable proto will cause error, but disable proto afterward has no effect.

---

run `bazel run //:gazelle`
then add `gazelle:proto disable` to BUILD
run `bazel run //:gazelle`

the generated BUILD for external still has the proto section

```bash
cat bazel-*/external/dev_go_micro_v4/debug/proto/BUILD.bazel
```

still has proto_library and go_proto_library

---

If I delete the `bazel-*/external/dev_go_micro_v4/debug/proto/BUILD.bazel`, run gazelle will not regenerate.

### What did you expect to see?

proto section are gone.

### What did you see instead?

proto section still there.

**Comment by achew22** [comment]
Gazelle doesn't delete targets that it doesn't have any knowledge about. This is an important feature, since you likely have rules in your repo that Gazelle doesn't manage for you `genrule`, `sh_{library,binary}`, as well as your custom rules.

In this case, you told Gazelle to create the proto rules by executing it with the default flags around protos, then told it that it wasn't in charge of managing it by adding the directive. If you'd like to remove these you can use something like `buildozer` and `bazel query` to remove the targets.

Best of luck with this!
