### ISSUE TITLE
support pkg config

### ISSUE THREAD

**Issue by jeb2239** [bazelbuild/bazel-gazelle#120]
is there a reason there is no support for pkg-config in cgo?

**Comment by jayconrod** [comment]
Gazelle doesn't support pkg-config because I don't think there's a way to generate build files that would work on different machines, which may have different versions of the library installed (or not installed at all) requiring different flags. At best, builds would be non-reproducible.

If Gazelle itself ran pkg-config, it would get flags that are specific to the system it runs on. It's quite likely those flags won't work for someone on another system.

If rules_go ran pkg-config, it would result in non-reproducible builds (though this may be unavoidable for these kinds of libraries). We can't run it from the sandbox, and we definitely can't run it with remote execution.

The best thing to do for these libraries is to build them from source with Bazel using `cc_library` rules, then add those to the `cdeps` attribute of the `go_library` that needs them. If that's infeasible, adding flags to `copts` and `clinkopts` with a `# keep` comment is probably the best alternative.
