### ISSUE TITLE
Support for go 1.18 "workspace" mode?

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/bazel-gazelle#1232]
Has anyone put any thought into gazelle support the new "workspace" mode added in go 1.18?

Some reference links:

Docs: https://go.dev/ref/mod#workspaces
Tutorial: https://go.dev/doc/tutorial/workspaces
Proposal: https://go.googlesource.com/proposal/+/master/design/45713-workspace.md
Discussion: https://github.com/golang/go/issues/45713

**Comment by gregmagolan** [comment]
cc @f0rmiga

**Comment by sluongng** [comment]
I am confused by the proposal language here

```
go.work files should not be checked into version control repos containing modules so that the go.work file in a module does not end up overriding the configuration a user created themselves outside of the module. The go.work documentation should contain clear warnings about this.
```

With this, it means that we should NOT be checking in go.work file.

In https://github.com/golang/go/issues/45713, my take out of this (very lengthy) discussion is that we should be building a tool that would generate the go.work file each time. So I wonder if @matloob or @jayconrod is willing to comment how this is supposed to be used in a Bazel monorepo.

---

With that said, Gazelle's Go extension work quite simple:

There are 3 main modes that its supporting: gopkg.lock, go.mod and godeps.json
https://sourcegraph.com/github.com/bazelbuild/bazel-gazelle@4af06e1c266f8e09b85405307c37fec03a71daab/-/blob/language/go/update.go?L61-65

Most likely we can just modify the code path for `go.mod` to make `go.work` works. These call should still be the same under `go.work`
```
go list -mod=readonly -e -m -json all
go mod download -json
```
https://sourcegraph.com/github.com/bazelbuild/bazel-gazelle@4af06e1c266f8e09b85405307c37fec03a71daab/-/blob/language/go/modules.go?L164-167

Im not yet sure how `go work sync` fit into the picture just yet, or if it's within Gazelle Go Extension's `update-repos` command scope at all.

**Comment by matloob** [comment]
`go.work` files are a feature of the `go` build system. From my understanding of Bazel (which is admittedly out of date) it's not totally clear to me that `go.work` files make sense or would provide anything useful for Bazel. The guidance to not check in `go.work` files should mean that they won't interfere with Bazel users' expectations from a build.

**Comment by sluongng** [comment]
@matloob in a bazel setup, we are currently using a single go.mod file to generate a bunch of `go_repository` targets to fetch external libraries into bazel before doing the build.

The obvious downside of this approach is that you can only have 1 go.mod file for the whole monorepo.
So folks really do want to have go.work to be setup in a monorepo with multiple modules.

Then we can use go.work to generate go_repository targets for the whole monorepo.

**Comment by sluongng** [comment]
Now that I have sometime to properly reading through the giant thread in https://github.com/golang/go/issues/45713, here are the conclusions that I have:

1. The recommendation for not checking in `go.work` to version control has been removed between the proposal to final documentation. There were several citation of Go Module `replace` directive had similar recommendation in the past, but folks checked in the `replace` directive anyway in order to solve their problems. So `go.work` can/should be checked into version control, especially for cases with monorepo with multiple modules, trying to use `go.work` to glue these modules into 1 giant big module.

2. `go work sync` command https://go.dev/ref/mod#go-work-sync was latter proposed and implemented as the mean to consistently sync the version used in workspace back down to each modules being used in workspace. This command helps ensuring that all modules in workspace are in synced with each other and avoid version conflict. This sounds like a must have for Bazel / Gazelle.

With that said, there should be no longer a blocker for implementing support for `go.work` in Gazelle's Go language extension as I was originally concerned.

**Comment by thempatel** [comment]
does this issue have a champion or do we need someone to pick up the work?
