### ISSUE TITLE
autogazelle package fails to build in Go version 1.19

### ISSUE THREAD

**Issue by tyler-french** [bazelbuild/bazel-gazelle#1332]
### What version of gazelle are you using?

master@HEAD

### What version of rules_go are you using?

0.33.0

### What version of Bazel are you using?

4.2.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Mac OS Intel

### What did you do?

Upgrade `go.mod` file to `go 1.19` and `WORKSPACE` to:
```
go_register_toolchains(
    nogo = "@bazel_gazelle//:nogo",
    version = "1.19",
)
```

### What did you expect to see?

No build errors.

### What did you see instead?

```
❯ bazel test //...
INFO: Analyzed 143 targets (4 packages loaded, 520 targets configured).
INFO: Found 114 targets and 29 test targets...
ERROR: /Users/tfrench/bazel-gazelle/cmd/autogazelle/BUILD.bazel:47:10: GoLink cmd/autogazelle/autogazelle_/autogazelle failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder link -sdk external/go_sdk -installsuffix darwin_amd64 -arc ... (remaining 19 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
2022/09/10 12:58:19 link: unlinkable object (from package golang.org/x/sys/unix) - compiler requires -p flag
link: error running subcommand external/go_sdk/pkg/tool/darwin_amd64/link: exit status 1
INFO: Elapsed time: 6.137s, Critical Path: 2.12s
INFO: 31 processes: 6 internal, 25 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

This is probably a similar issue to https://github.com/bazelbuild/rules_go/issues/3199

**Comment by wamuir** [comment]
`bazel test //...` succeeds for me (linux amd64) with `go.mod` and `WORKSPACE` at Go 1.19, but only after upgrading `rules_go` to >= 0.34.0.  It fails as described in this issue with `rules_go` at 0.33.0.

Another data point, as this issue is listed as a blocker for #1323: `bazel test //...` succeeds for [tyler-french/bazel-gazelle:new-release](https://github.com/tyler-french/bazel-gazelle/tree/new-release) (`rules_go` = 0.34.0) with Go 1.19 upgrade in `go.mod` and `WORKSPACE`.

**Comment by linzhp** [comment]
Yeah, it seems to work with rules_go 0.35 too: #1349
