### ISSUE TITLE
Instruct gazelle to include some top-level files as test data

### ISSUE THREAD

**Issue by astratto** [bazelbuild/bazel-gazelle#135]
**Problem:** in a project I'm working on some top-level files are required for testing and I'd like a way to tell gazelle to always add them as `data = [...]` section (or even better to a pattern of subdirectories), in addition to whatever is in a `testdata` directory.

I couldn't find a way to do it, am I missing any option?

**Comment by jayconrod** [comment]
There's no way to do this with Gazelle automatically, but Gazelle won't remove `data` attributes from existing rules after you add them. The best way to add them is probably [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) which is a general purpose tool for batch modifications to build files.

Something like this might work:

```
buildozer 'add data //:testfiles' label1 label2...
```

**Comment by astratto** [comment]
Uhm, that's what I suspected. Thanks!
I'm doing something similar with `awk`, pretty much same results.

The main problem here is that I'm trying to skip the analysis phase in Bazel, because I'm generating those files on the flight and that phase takes ~1 minute.
But I've recently noticed that just re-running `gazelle` with no changes triggers that phase, so I guess the real issue for me lies somewhere else.

**Comment by jayconrod** [comment]
Closing, since it isn't clear Gazelle should do something differently with `data`. But feel free to re-open if that's not the case.

The issue with re-running `gazelle` causing analysis to run again sounds like it might be a problem. Is that with standalone gazelle or with `bazel run //:gazelle`? And it's slow on the next run? Please open a new issue if something's slower than it seems like it should be. Need more information to investigate though.

**Comment by astratto** [comment]
Thanks Jay, sure let's close this.
Sorry I didn't get back to you, but I've paused my work on this, mostly (but not only) due to this issue.

I'll re-open it in case I have a chance to play around with this again.
