### ISSUE TITLE
build files are not updated even when build_file_generation = "on"

### ISSUE THREAD

**Issue by roundhd** [bazelbuild/bazel-gazelle#1535]
### What version of gazelle are you using?
HEAD [98250fb](https://github.com/bazelbuild/bazel-gazelle/commit/98250fbf6c73b48d006e6081c582eeb8c9333fc8)

### What version of rules_go are you using?
v0.39.0

### What version of Bazel are you using?
6.1.1

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
darwin/arm64

### What did you do?

I used the following go_repository rule:
```
go_repository(
    name = "com_github_mwitkow_go_proto_validators",
    build_file_proto_mode = "disable_global",
    importpath = "github.com/mwitkow/go-proto-validators",
    build_file_generation = "on",
    sum = "h1:qRlmpTzm2pstMKKzTdvwPCF5QfBNURSlAgN/R+qbKos=",
    version = "v0.3.2",
)
```

### What did you expect to see?
I expected that the build files in `external/com_github_mwitkow_go_proto_validators` would be updated.

### What did you see instead?
The build files in `external/com_github_mwitkow_go_proto_validators` are not updated and appear to be out of date for usage.

**Comment by alexeagle** [comment]
Discussed with @fmeum on Slack - I think what's really wanted here is not to change the existing mode for `build_file_generation` but rather to add a new one like `replace`, otherwise similar to your PR.

This would be useful in cases where we run into https://github.com/bazelbuild/bazel/issues/19301 under bzlmod, but didn't actually want any of the "Bazel module" content from the package in question, we just want a pure Go package. Erasing all BUILD files before generation solves for that case.

**Comment by fmeum** [comment]
Cc @linzhp 

Contributions for this new mode would be very welcome.

**Comment by fmeum** [comment]
This has been fixed in https://github.com/bazelbuild/bazel-gazelle/pull/1802.
