### ISSUE TITLE
gazelle fix does not fix visibility of internal packages

### ISSUE THREAD

**Issue by devnev** [bazelbuild/bazel-gazelle#177]
Steps to reproduce:
- In an existing Go repository, run gazelle to generate build files.
- Create an `internal` directory in the repository.
- Move an existing package into the `internal` directory.
- run gazelle fix.

Expected result:
- The go_library rule in the moved build file has its visibility updated to `...:__subpackages__` to match how the Go compiler will treat the package.

Observed result:
- The go_library rule keeps its previous visibility.

**Comment by jayconrod** [comment]
Sorry for the delayed response. I was out of the office for the last week.

This is working as intended. `visibility` is a non-mergeable attribute, which means that Gazelle won't change `visibility` attributes on existing rules, but it will add them if they are missing. `visibility` is non-mergeable because it's more likely to be changed by a manual edit rather than an automatic edit.

In general, Gazelle can't distinguish between rules that were moved to a new location and rules that were manually edited. It doesn't have any state between runs, other than the contents of sources and build files.
