### ISSUE TITLE
gazelle:resolve_regexp should support regex in label

### ISSUE THREAD

**Issue by lkassar-stripe** [bazelbuild/bazel-gazelle#1821]
### What version of gazelle are you using?

0.33.0

### What version of rules_go are you using?

0.41.0
### What version of Bazel are you using?

7.0.1
### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?

macOS Sonoma 14.0, arm64

### Issue

Context: We maintain a large golang repository with gazelle, and we would like gazelle to manage resolution for importpaths that point to targets in an external repository that we have. Although the `gazelle:repository` directive exists, since it operates heuristically, the importpath doesn't match the expected target name that gazelle attempts to resolve it to. 

We would like to use the `gazelle:resolve_regexp` to solve this. `gazelle:resolve_regexp` has an argument for the import-string-regexp and the label it matches to. We'd like to support the label also being a regexp, and populate that regexp with matches from the import-string-regexp. 

I have a change that would do this, which I will PR after creating this issue, but would like some feedback on the possibility of supporting this in bazel-gazelle, as folks on our team have expressed that this seems intuitive change to the existing directive and would allow us the possibility to use this for many upcoming cases where we need to manipulate gazelle resolves.

**Comment by jeromep-stripe** [comment]
@linzhp Hi again! Any chance you could evaluate this when you have a moment? @lkassar-stripe also has a PR ready.

**Comment by linzhp** [comment]
I can take a look later this week

**Comment by negator** [comment]
Any updates here? Our company (vsco.co) uses gazelle heavily, however we are facing a similar issue as the OP. Namely we have some 50+ generated `go_proto_library` rules that are not indexable by gazelle, and which are continually updated. I.e. they are not defined statically in BUILD files. So we must use `resolve` annotations for each and every one. We'd like the ability to use regex captures to enable us to use a single `resolve_regexp` rather than many.

**Comment by linzhp** [comment]
@tyler-french is reviewing the PR
