### ISSUE TITLE
Support bazel tags for integration tests with +build integration

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/bazel-gazelle#188]
Would you be open to a PR that adds tags to the bazel rules depending on the `+build` flags?
Similar to this
https://github.com/bazelbuild/rules_go/issues/867#issuecomment-333980653

Or if there is already a better way to do it, please let me know.

**Comment by jayconrod** [comment]
I think you can already do this.

* Run Gazelle with `-build_tags=integration` (or any comma-separated list of tags). It will treat those tags as true and will include tagged sources in `srcs` lists of relevant rules.
* When running Bazel, add `--define gotags=integration` (comma-separated again) on the command line. This will include tagged source files at build time.

**Comment by codesuki** [comment]
I get it now! Instead of having 2 bazel rules one for integration, one for unit and using bazel tags you just use the go-way. Are there any plans to use bazel tags in the future?

**Comment by jayconrod** [comment]
We don't have any plans at the moment to translate Go tags to Bazel tags. Go tags are a lot more flexible for controlling the build since Go supports conjunction, disjunction, and negation on individual files.

Bazel tags are a simple list on rules. They're more useful for querying. There are also a number of tags with special meaning (see [common attributes](https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes)).

**Comment by codesuki** [comment]
Thanks for clearing that up and thanks for the good work!

**Comment by seh** [comment]
I can see that `--define` can define a Go build tag when supplied as a command-line flag. Is there any way to include such a tag in a `go_binary` target, or maybe a `go_library` target? In my case, it's not a platform-dependent condition, so using the filename suffix doesn't seem like an adequate solution.

**Comment by jayconrod** [comment]
@seh There's no way set tags on `go_binary` or `go_library` right now.

Bazel has an [experimental feature](https://docs.bazel.build/versions/master/starlark_config.html) for defining command line flags that can also be manipulated in transitions in Starlark rules. Build tag functionality will be rewritten when that's fully rolled out. A feature like this would easier to support after that's done.

**Comment by clstb** [comment]
> I get it now! Instead of having 2 bazel rules one for integration, one for unit and using bazel tags you just use the go-way. Are there any plans to use bazel tags in the future?

I don't quite understand what is meant by "the go-way". I am aware that it is possible to generate `go_test` rules based on build tags using gazelle. In order to change the type of testing it is needed to re run gazelle passing the corresponding `build_tags`. Because `BUILD` files are checked into vcs this results in a lot of noise. Is there another way to select tests post-gazelle without manually adding bazel tags to `BUILD` files?

I've also seen the comment about `--define gotags=integration` but this does not seem to make a difference running `bazel test //...`.
