### ISSUE TITLE
gazelle 0.12.0 loses select clause

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel-gazelle#205]
I have a go_library that specifically cannot build on anything but amd64, and upgrading to 0.12.0 from 0.10.1 causes runs of //:gazelle to turn the below:

```
 go_library(
     name = "go_default_library",
     srcs = [
         "model.go",
         "suffix_gen.go",
         "twitter.go",
       ] + select({
       "@io_bazel_rules_go//go/platform:amd64": [
           "convert_amd64.go",
       ],
       "//conditions:default": [],
   }),
   ],
  ... yadda yadda
```

into 

```
go_library(
    name = "go_default_library",
    srcs = [
        "convert_amd64.go",
        "model.go",
        "suffix_gen.go",
        "twitter.go",
    ],
... yadda yadda
```

**Comment by jayconrod** [comment]
This is now the intended behavior for the `srcs` attribute only. `deps` and other attributes will still be emitted with `select` expressions though. See #134.

The issue was that when people use `goos` and `goarch` attributes in `go_binary` and `go_test`, the `select` expressions pick the wrong values. Bazel interprets `select` expressions before the analysis phase, and we cannot affect its behavior with attributes. To slightly mitigate this, we decided to stop using `select` expressions in `srcs`. They are largely unnecessary since rules_go also filters source files using build constraints during the execution phase. (For reference, `--platforms` is a much better option than `goos` / `goarch` attributes for cross compilation).

Since your library can't build on anything except amd64, make sure that everything depends on it via a `select` expression. You may also want to add `tags = ["manual"]` to the rule to ensure `bazel build //...` doesn't pick it up. Alternatively, you could add an `_amd64` filename suffix or a `// +build amd64` comment to all source files so that if the library is built for the wrong platform, it's empty.

**Comment by jmhodges** [comment]
Ahh, thank you. I previously had taken out the amd64 build tag because, of course, rules_go didn't support that but now, of course, it does!
