### ISSUE TITLE
Custom GOPATH not working correctly.

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/bazel-gazelle#218]
So I have a repository which is laid out as follows:

```
/
/src
/src/{projectName}/shared/{pkgName}
/src/{projectName}/services/{serviceName}
/src/{projectName}/services/{serviceName}/vendor
/src/{projectName}/entrypoints/{entrypointName}
/src/{projectName}/entrypoints/{entrypointName}/vendor
```

Here is the build file in the root of the repository:

```
package(default_visibility = ["//visibility:public"])

load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix src

gazelle(
    name = "gazelle",
    external = "vendored",
)
```

However the vendored files works fine so files at `/src/{projectName}/services/introducers-gw/vendor/github.com/sirupsen/logrus/` have a dep of `//src/{projectName}/services/introducers-gw/vendor/github.com/sirupsen/logrus:go_default_library`

However the files within the same package `/src/{projectName}/services/introducers-gw/pkg/generated/restapi/` have a dep of `//vendor/{projectName}/services/introducers-gw/pkg/generated/restapi:go_default_library` which of course is wrong.

Is this a bug or am I doing something wrong?

**Comment by jayconrod** [comment]
Could you double-check the `importpath` attributes of non-vendored `go_library` rules? I think you are going to end up with something like `importpath = "src/src/{projectName}/services/{serviceName}"` instead of `importpath = "{projectName}/services/{serviceName}"`.

Gazelle resolves dependencies using the `importpath` attributes in `go_library` rules. It generates `importpath` attributes for each library by concatenating the prefix (set with `-go_prefix` on the command line or `# gazelle:prefix` in build files) with the relative path from the directory where the prefix was set to the library.

So in this case, you can create a file `src/BUILD.bazel` that sets an empty prefix (`# gazelle:prefix`). The `importpath` for libraries generated in the `src` directory will be the empty prefix concatenated with the relative path below `src`, e.g., `{projectName}/services/{serviceName}`.

**Comment by bweston92** [comment]
Wow that worked. I didn't understand what you said but it worked.
