### ISSUE TITLE
"duplicate proto types registered"; "duplicate extension registered" after incorporating Google Cloud pubsub

### ISSUE THREAD

**Issue by cdelguercio** [bazelbuild/bazel-gazelle#225]
I suspect this is related to my issue #201. I'm using master for rules_go and bazel-gazelle.

After I added a component that depends on Google Cloud pubsub to my Go source, my code still compiles, but when I try to run it I get the following:

```
2018/06/04 23:48:21 proto: duplicate proto type registered: google.api.Http
2018/06/04 23:48:21 proto: duplicate proto type registered: google.api.HttpRule
2018/06/04 23:48:21 proto: duplicate proto type registered: google.api.CustomHttpPattern
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterExtension(0x1150420)
	external/com_github_golang_protobuf/proto/extensions.go:533 +0x2e7
google/api.init.2()
	bazel-out/k8-opt/bin/external/googleapis_archive/linux_amd64_stripped/api_go_proto~/google/api/annotations.pb.go:32 +0x2d
```

I suspect the problem is my googleapis.BUILD where I reference @com_github_golang_protobuf:

```
proto_library(
    name = "api_proto",
    srcs = [
        "google/api/http.proto",
        "google/api/annotations.proto",
    ],
    deps = ["@com_google_protobuf//:descriptor_proto"],
)

go_proto_library(
    name = "api_go_proto",
    importpath = "google/api",
    proto = ":api_proto",
    deps = [
        "@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library",
    ],
)
```

Here's the relevant part of my WORKSPACE:

```
http_archive(
    name = "com_google_protobuf",
    sha256 = "56b5d9e1ab2bf4f5736c4cfba9f4981fbc6976246721e7ded5602fbaee6d6869",
    strip_prefix = "protobuf-3.5.1.1",
    urls = ["https://github.com/google/protobuf/archive/v3.5.1.1.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_go",
    url = "https://github.com/bazelbuild/rules_go/archive/1903997d0945ce92848447528718c7026b728f30.tar.gz",  # June 1, 2018
    strip_prefix = "rules_go-1903997d0945ce92848447528718c7026b728f30",
    sha256 = "c4d602a4b5204bae8e7c5cf3f916845b2cef539741d020b1e1bba09d843259b2",
)
http_archive(
  name = "bazel_gazelle",
  url = "https://github.com/bazelbuild/bazel-gazelle/archive/644ec7202aa352b78d65bc66abc2c0616d76cc84.tar.gz",  # May 31, 2018
  strip_prefix = "bazel-gazelle-644ec7202aa352b78d65bc66abc2c0616d76cc84",
  sha256 = "ef1722f82aed4d312779e9357391b8715a0933a880d84031dde649ecac605274",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()

new_http_archive(
    name = "googleapis_archive",
    build_file = "//third_party:googleapis.BUILD",
    sha256 = "df585427959ebb9949ca12a45888b50a5b8edcb2b270aea1800225d159a49ff6",
    strip_prefix = "googleapis-3273178ea4684acc4f512f7bef7349dd72db88f6",
    urls = ["https://github.com/googleapis/googleapis/archive/3273178ea4684acc4f512f7bef7349dd72db88f6.tar.gz"],
)


go_repository(
    name = "com_google_cloud_go",
    importpath = "cloud.google.com/go",
    tag = "v0.23.0",  # May 18, 2018
)

go_repository(
    name = "org_golang_google_api",
    importpath = "google.golang.org/api",
    commit = "00e3bb8d04691e25ee2fccf98c866bcb7925c3ec",  # June 5, 2018
)

go_repository(
    name = "org_golang_x_sync",
    importpath = "golang.org/x/sync",
    commit = "1d60e4601c6fd243af51cc01ddf169918a5407ca",  # March 14, 2018
)

go_repository(
    name = "org_golang_x_oauth2",
    importpath = "golang.org/x/oauth2",
    commit = "cdc340f7c179dbbfa4afd43b7614e8fcadde4269",  # May 2, 2018
)

go_repository(
    name = "io_opencensus_go",
    importpath = "go.opencensus.io",
    tag = "v0.12.0",  # June 5, 2018
)

go_repository(
    name = "com_github_googleapis_gax_go",
    importpath = "github.com/googleapis/gax-go",
    tag = "v2.0.0",  # September 14, 2017
)
```

Thanks for reading!

**Comment by jayconrod** [comment]
From the error, it does sound like there is some conflict. Maybe multiple copies of the same proto are getting compiled?

Your googleapis.BUILD and WORKSPACE files seem okay. I was able to paste them into an empty workspace and build `@googleapis_archive//:api_go_proto` without error. Any chance you could post a small test repo that reproduces this problem?

**Comment by cdelguercio** [comment]
https://github.com/cdelguercio/pubsub_problem
```
git checkout not-working
bazel build //...
./bazel-bin/server/linux_amd64_stripped/server
```
```
git checkout working
bazel build //...
./bazel-bin/server/linux_amd64_stripped/server
```

**Comment by jayconrod** [comment]
Thanks for posting that repro. That helped enormously. I figured out a way to make this work (see patch below). Sorry things are a mess. We should really make this a lot easier.

The error is getting reported because `google.api.Http` is getting registered with the proto system more than once. This is not due to an `importpath` conflict; `http.pb.go` is compiled into two libraries with different import paths, so the compiler and linker don't complain about this.

I started by creating a [`go_path`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path) rule that puts all the transitive sources for `//server` in one directory.

```
load("@io_bazel_rules_go//go:def.bzl", "go_path")

go_path(
    name = "go_path",
    deps = ["//server"],
)
```

I grepped this for `"google.api.Http"` and found that type was registered in two files:

*  `google/api/http.go` a.k.a. `@googleapis_archive//:api_go_proto`
* `google.golang.org/genproto/googleapis/api/annotations/http.pb.go` a.k.a. `@org_golang_google_genproto//googleapis/api/annotations:go_default_library`

`@org_golang_google_genproto` is declared by rules_go. It contains `go_library` rules for pre-generated .pb.go files for everything in googleapis. `@com_google_cloud_go//pubsub:go_default_library` depends on the annotations library from that repo, so to avoid conflicts, that's the one you have to use.

Unfortunately, `@com_golang_google_genproto` doesn't include the .proto files or `proto_library` rules, and since you're building your own protos against those, you need to get them from somewhere. Your `proto_library` declaration in `googleapis.BUILD` seems fine for that, but the `go_proto_library` in there needs to be removed.

To summarize:

* Remove `@googleapis_archive//:api_go_proto` and anything redundant with libraries in `@org_golang_google_genproto`.
* Update anything that depended on `@googleapis_archive//:api_go_proto` to depend on `@org_golang_google_genproto//googleapis/api/annotations:go_default_library` instead.

```
diff --git a/api/service/BUILD.bazel b/api/service/BUILD.bazel
index ea8cf5f..ee2904c 100644
--- a/api/service/BUILD.bazel
+++ b/api/service/BUILD.bazel
@@ -16,7 +16,7 @@ go_grpc_library(
     proto = ":proto",
     visibility = ["//visibility:public"],
     deps = [
-        "@googleapis_archive//:api_go_proto",
+        "@org_golang_google_genproto//googleapis/api/annotations:go_default_library",
     ],
 )
 
diff --git a/third_party/googleapis.BUILD b/third_party/googleapis.BUILD
index 63310ab..41dac79 100644
--- a/third_party/googleapis.BUILD
+++ b/third_party/googleapis.BUILD
@@ -10,12 +10,3 @@ proto_library(
     ],
     deps = ["@com_google_protobuf//:descriptor_proto"],
 )
-
-go_proto_library(
-    name = "api_go_proto",
-    importpath = "google/api",
-    proto = ":api_proto",
-    deps = [
-        "@com_github_golang_protobuf//protoc-gen-go/descriptor:go_default_library",
-    ],
-)
```

Gazelle is going to need to be a lot smarter in order to deal with this. Gazelle works well for Go because "go build" requires that fairly strong conventions are followed with respect to import paths and directories. Protos don't follow such strong conventions, and pre-generated code is frequently checked in and used. I'm going to leave this issue open as an experience report, and I hope we can improve this soon. There's no simple fix though.

**Comment by cdelguercio** [comment]
This fix worked! Thanks so much @jayconrod, you're a legend!
