### ISSUE TITLE
Package name must be the same with directory name?

### ISSUE THREAD

**Issue by erjiaqing** [bazelbuild/bazel-gazelle#271]
While I'm building my project with `bazel build //...` it failed with:

```
$ bazel build //...

INFO: Analysed 18 targets (0 packages loaded).
INFO: Found 18 targets...
ERROR: /home/<username>/.cache/bazel/_bazel_<username>/<hash>/external/com_github_googleapis_gnostic/extensions/BUILD.bazel:18:1: GoCompile external/com_github_googleap
is_gnostic/extensions/linux_amd64_stripped/go_default_library~/github.com/googleapis/gnostic/extensions.a failed (Exit 1)
/home/<username>/.cache/bazel/_bazel_<username>/<hash>/sandbox/linux-sandbox/3/execroot/platformoperator/external/com_github_googleapis_gnostic/extensions/extensions.go
:15:9: package openapiextension_v1; expected extensions
GoCompile: error running subcommand: exit status 2
INFO: Elapsed time: 1.037s, Critical Path: 0.36s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

after I change it to `package extensions` manually, it no longer complain about this

if I build with `go build` manually, it finished without any issue

gazelle version: `0.13.0`

**Comment by jayconrod** [comment]
Thanks for reporting! I think this is actually a problem with `go_proto_library`, not Gazelle. The problem comes up in `github.com/googleapis/gnostic/extensions`.

There's no `option go_package` statement in the .proto here, so Gazelle sets `importpath` correctly to `github.com/googleapis/gnostic/extensions`. I think we're passing that path into protoc-gen-go, and it thinks the package name in the generated .pb.go file should be `extensions`. That's incompatible with the other .go file in the directory, and it's different from what protoc generates by default, which should be `openapiextension_v1`.

I've filed bazelbuild/rules_go#1596 to track this going forward.

**Comment by tristanz** [comment]
For future folks, you can also get around this by adding `build_file_proto_mode = "disable_global"` to the go_repository rule since the pb.go files already exist in the googleapis/gnostic repo.  For instance:

```
go_repository(
    name = "com_github_googleapis_gnostic",
    commit = "0c5108395e2d",
    importpath = "github.com/googleapis/gnostic",
    build_file_proto_mode = "disable_global",
)
```
