### ISSUE TITLE
Support a "ignore vendor" build_external mode in gazelle and go_repository

### ISSUE THREAD

**Issue by chrismcbride** [bazelbuild/bazel-gazelle#300]
Here is a minimal example of a project that cannot build with go_repository:

WORKSPACE:

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "5756a4ad75b3703eb68249d50e23f5d64eaf1593e886b9aa931aa6e938c4e301",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.14.0/rules_go-0.14.0.tar.gz"],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "c0a5739d12c6d05b6c1ad56f2200cb0b57c5a70e03ebd2f7b87ce88cabf09c7b",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.14.0/bazel-gazelle-0.14.0.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

go_repository(
    name = "com_github_heroku_docker_registry_client",
    commit = "fd2fe803496897db70c236ee244f41487ea92ec2",
    importpath = "github.com/heroku/docker-registry-client",
)

go_repository(
    name = "com_github_opencontainers_go_digest",
    commit = "279bed98673dd5bef374d3b6e4b09e2af76183bf",
    importpath = "github.com/opencontainers/go-digest",
)
```

BUILD.bazel:

```python
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "main",
    srcs = [
        "main.go",
    ],
    deps = [
        "@com_github_heroku_docker_registry_client//registry:go_default_library",
        "@com_github_opencontainers_go_digest//:go_default_library",
    ],
)
```

main.go:

```go
package main

import (
	"github.com/heroku/docker-registry-client/registry"
	"github.com/opencontainers/go-digest"
)

func main() {
	reg, _ := registry.New("myregistry.com", "user", "pass")
	layerDigest := digest.FromString("myLayer")
	reg.HasLayer("repo", layerDigest)
}
```
I get the following compile error when running ```bazel build ...``` (Im using bazel version 0.15):

```
main.go:11:15: cannot use layerDigest (type "github.com/opencontainers/go-digest".Digest) as type "github.com/heroku/docker-registry-client/vendor/github.com/opencontainers/go-digest".Digest in argument to reg.HasLayer
GoCompile: error running subcommand: exit status 2
Target //:main failed to build
```

The issue here is that `heroku/docker-registry-client` has a vendored copy of `opencontainers/go-digest`, and it also accepts types from `opencontainers/go-digest` in its public API. I would like gazelle to generate a BUILD file that uses the external version of go-digest (`@com_github_opencontainers_go_digest//:go_default_library`) instead of the vendored.  I've commented on issue #269 believing this to be a bug but after reading [dependency resolution](https://github.com/bazelbuild/bazel-gazelle#dependency-resolution) more carefully I realize this is by design. Gazelle will always find the vendored version at step number 3 regardless of the build_external flag that is passed in via go_repository.

Im proposing we either change build_external to ignore vendor directories if set to "external" or we add a third mode that does so. Im willing to work on the PR if this issue is approved.

**Comment by jayconrod** [comment]
The current behavior is by design (I'll explain why below), but a lot of people have reported similar errors, and I think it would be useful to have a simple way to deal with this.

I'm thinking about adding a "strict" mode where Gazelle does not index libraries in a repository and resolves dependencies solely based on the import path, prefix, and external mode. So basically, this would skip step 3. The main reason I want this is so that Gazelle could be run in individual directories very quickly (e.g., from an editor save hook), but it would also be useful in this situation. You would be able to set "strict" on a `go_repository` rule, and Gazelle would ignore the vendor directory.

The reason why the current behavior is by design is because it's what "go build" does. When I pasted this example into a local directory and ran `go build .`, it actually gives me the same error you reported. This happens because the vendor directory in `github.com/heroku/docker-registry-client` is private to that repository, but the vendored types leak into the public API, so they cause conflicts. The charter of Gazelle and `go_repository` is to map the semantics of "go build" to Bazel, so the fact that we get the same error is good.

That being said, there ought to be an easy way to work around this without building your own vendor directory.

**Comment by chrismcbride** [comment]
Ah I see, thanks for the explanation. I suppose library authors shouldn't be checking in vendor directories at all then?

I agree that the strict mode sounds nice. For now Ill try to write BUILD files by hand for libraries that leak vendored types like this.

**Comment by Xjs** [comment]
> I'm thinking about adding a "strict" mode where Gazelle does not index libraries in a repository and resolves dependencies solely based on the import path, prefix, and external mode. So basically, this would skip step 3. The main reason I want this is so that Gazelle could be run in individual directories very quickly (e.g., from an editor save hook), but it would also be useful in this situation. You would be able to set "strict" on a go_repository rule, and Gazelle would ignore the vendor directory.

+1! Depending on e. g. https://github.com/docker/docker with `go_repository` is very painful nowadays and requires us to fork the docker/* repositories and remove the vendor directories in the fork.

**Comment by terinjokes** [comment]
I'm also getting this behavior importing from [k8s.io/kubernetes/pkg/util/iptables](https://github.com/kubernetes/kubernetes/tree/master/pkg/util/ipconfig). The API expects a type from [k8s.io/utils/exec](https://github.com/kubernetes/utils/tree/master/exec) that I can't fulfill because it's been vendored.

I don't have them problem with dep, as it gets flattened.

**Comment by jayconrod** [comment]
#300 should provide a language-neutral way to fix this. You can use it like this:

```
go_repository(
    name = "com_example_foo",
    importpath = "example.com/foo",
    commit = "123456",
    build_extra_args = ["-exclude=vendor"],
)
```

**Comment by terinjokes** [comment]
@jayconrod Lovely, I'll have to give it a shot. Any chance of a 0.15.1 with this?

**Comment by jayconrod** [comment]
@terinjokes Sorry, point releases only get bug fixes, not new features. This will be in the next major release, which should be in the first half of November.

You can reference the commit that adds this from your WORKSPACE though. `master` is pretty stable these days.

**Comment by terinjokes** [comment]
Can confirm, this patch fixes my issue with the Kubernetes packages described above.

**Comment by chrismcbride** [comment]
Confirmed the problem is solved for me as well, thanks!

**Comment by filmil** [comment]
@jayconrod Do I see it correctly that there has not been a release since this was fixed.  First half of November was a month ago, what gives?

**Comment by jayconrod** [comment]
@filmil My time is spread out on several projects, and I'm not always able to give accurate estimates. In this case, I still need to change a public API before tagging a major release.

You can always use a newer (untagged) commit. `master` is pretty stable.

**Comment by filmil** [comment]
Sorry, what I meant was to check if I just missed a release somehow.  Indeed, taking bazel-gazelle from current HEAD worked fine.
