### ISSUE TITLE
Support converting Gopkg.lock into a .bzl file instead of mutating WORKSPACE

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel-gazelle#301]
Current Gazelle's support for converting Gopkg.lock into `go_repository()` calls will actually append those calls to the global `WORKSPACE` file, which makes it difficult to manage. It'd be nice if it could be told to write to a `.bzl` file instead with a wrapper function, which the user could load into `WORKSPACE` at the proper location.

**Comment by robfig** [comment]
@jayconrod would you be open to a contribution for this feature? If so, do you have guidance on how you would like it approached? I'm not currently familiar with the Gazelle codebase, but I could probably get something together in the next month and a half.

**Comment by jayconrod** [comment]
@robfig The hard part about implementing this would be updating the rule generation and merging logic.

[rule.go](https://github.com/bazelbuild/bazel-gazelle/tree/master/internal/rule) contains code for creating, updating, and deleting rules in build files. This pretty strongly assumes that rules looks like top-level function calls, but maybe that assumption can be relaxed.

[merger.go](https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/merger/merger.go) is where we merge a generated file with an existing file. This relies heavily on logic in the `rule` package.

So maybe it should work like this:

* User runs `gazelle update-repos -from_file=... -to_macro=repositories.bzl%go_repositories`. The last argument is new. That would tell Gazelle to modify the body of the `go_repositories` function in `repositories.bzl`.
* We generate a list of `go_repository` rules. [`ImportRepoRules`](https://github.com/bazelbuild/bazel-gazelle/blob/e70995a016131c86f4be93978c7624e6a2760414/internal/repos/repo.go#L74) does this.
* [`merger.MergeFile`](https://github.com/bazelbuild/bazel-gazelle/blob/e70995a016131c86f4be93978c7624e6a2760414/internal/merger/merger.go#L47) needs to be updated to be able to merge rules into the body of a function instead of the top-level of the file.  This may require changes in the `rule` package or the `merger` package. I'm not sure which would be cleanest. Likely `rule`.
* [update-repos.go](https://github.com/bazelbuild/bazel-gazelle/blob/master/cmd/gazelle/update-repos.go) needs to support the new flag, and it needs to update the `load` statements in the target .bzl file instead of WORKSPACE. It probably shouldn't call `merger.FixWorkspace` or `merger.CheckGazelleLoaded` if the flag is given.
