### ISSUE TITLE
Gazelle source-layout compatibility question

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#304]
Hi,

I want to migrate a repo at work to use Bazel and Gazelle. Since it's a polyglot repo, to work with GOPATH we checked in all of our Go code under `//gocode/src/corp/...` and use glock to sync third party dependencies (git-ignored) under //gocode/src/github.com/... (and similar).

I'm having trouble getting this setup working with Gazelle. 

```
$ bazel run //:gazelle -- gocode/src/corp 
```
gets close, but then Gazelle does not rewrite third party imports, using this instead:

```
    deps = [
        "//gocode/src/corp:go_default_library",
        "//gopkg.in/yaml.v2:go_default_library",
    ],
```

This is fixed if I do
```
$ bazel run //:gazelle -- -repo_root gocode/src/corp gocode/src/corp 
```

but then Gazelle fails to prefix same-repo imports with //gocode/src/corp.
```
    deps = [
        "//:go_default_library",
        "@in_gopkg_yaml_v2//:go_default_library",
    ],
```

Here's an example repo demonstrating the setup:
https://github.com/robfig/gazelleexample

Do you have any advice how Gazelle can handle this? If it can not, what change to source layout do you recommend?

Thank you,
Rob

**Comment by jayconrod** [comment]
Sorry for the slow response. I was at GopherCon last week, then went offline for a few days.

Just to confirm my understanding, here's your repository layout:

```
WORKSPACE                  # at repository root
gocode/src/corp/...        # your code is here
gocode/src/github.com/...  # other third-party code is also in gocode/src
javacode/...               # other languages are also in this repo
```

In cases where you have a GOPATH directory checked in, you can create an otherwise empty build file in `gocode/src` with the comment `# gazelle:prefix`. This sets the prefix to the empty string. A package at `gocode/src/corp/foo` should have `importpath = "corp/foo"`. A package at `gocode/src/gopkg.in/yaml.v2` should have `importpath = "gopkg.in/yaml.v2"`, and Gazelle should resolve the dependency correctly. Gazelle's dependency resolution is largely based on the `importpath` attributes, so check that those are correct.

You should always set `-repo_root` to the directory containing the WORKSPACE file. Gazelle won't index libraries in directories outside of the repo root.

**Comment by robfig** [comment]
Thanks for the response! Your understanding is exactly right. Thank you for the instruction around repo_root.

Since we don't want to check in our third party dependencies, that leaves us with two options:
- Use gazelle in external mode and configure it to write BUILD files referencing gopkg.in as "@in_gopkg_yaml_v2"
- Use a separate tool to download them into a GOPATH directory structure, and somehow overlay gazelle-produced BUILD files over them (seems harder and more complicated, so not planning to do this)

I was trying to use Gazelle to implement the first option. Gazelle was writing the third party dependency "gokpkg.in/yaml.v2" as "//gopkg.in/yaml.v2:go_default_library" instead of "@in_gopkg_yaml_v2//". I realized that I could resolve this by specifying `# gazelle:prefix WORKSPACE` at the WORKSPACE level, to force Gazelle to use external references for dependencies.

This issue is resolved now, thank you.
