### ISSUE TITLE
Support for generating custom rules

### ISSUE THREAD

**Issue by akshayjshah** [bazelbuild/bazel-gazelle#311]
Virtually all the logic in Gazelle is a good fit for me: directive support, parsing source code, etc. are all perfect. However, I need to generate slightly different rules than Gazelle's default `go_library`, `go_test`, etc. Today, the only way I can see to do this is to fork Gazelle and change `internal/language/go/kinds.go` (and any related code). Is this correct?

If so, do you have plans to make Gazelle more extensible in the future? I suspect that this use case is relatively common, since many large-ish organizations have their own ideas about how Go should be built, tested, linted, and formatted by default. It'd be great if Gazelle exposed a way to let users supply their own set of rules.

**Comment by jayconrod** [comment]
@akshayjshah Are you interested in generating alternate rules for Go (e.g., `go_image` instead of `go_binary`) or are you interested in generating other kinds of rules (e.g., libraries, binaries, and tests for other languages; other code generators)? Is it important that those rules are integrated with the Go rules, or can they be separate?

I did a major refactoring of Gazelle a while ago to make it easier to add support for other languages (you can add new packages under internal/language). I've been thinking about ways to build custom versions of Gazelle that incorporate those additional packages without needing them to be part of the main Gazelle repo.

**Comment by akshayjshah** [comment]
For Go, I'd like to generate some rules in addition to the ones Gazelle puts out. It'd be fine for those rules to be separate from Gazelle's. However, I'll also need an entirely separate implementation of the protobuf rules (since our non-monorepo code compiles a little idiosyncratically, and we'll want compatibility during our transition to a monorepo). I'll also also need to build a Thrift equivalent to the protobuf rules.

I'm monkeying around with the internals of the language package now; as you say, it's easy to add/alter all these bits and pieces in my fork. I can imagine a few different ways to make this extensible in Gazelle itself, but if you have a design in mind I'm happy to go with that and open a PR.

**Comment by jayconrod** [comment]
I'm probably not ready for a PR yet, but I'll explain what I'm thinking. Eventually, I'd like to support something like this:

```
load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    extensions = ["//my/custom/ext:go_default_library"],
)
```

So that would build and run a custom gazelle binary with additional extensions. Ideally, the current languages (proto and go) would just be defaults for that attribute and would not be special. There probably needs to be some mechanism to determine the order extensions are run (e.g., go depends on proto, so proto must run first).

It's probably best to keep a fork for now. Note that you can run the `gazelle` rule on a custom binary that accepts the same command line args:

```
load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    gazelle = "//my/custom/fork",
)
```
