### ISSUE TITLE
Flatten out go_repository's vendor with dep vendors

### ISSUE THREAD

**Issue by karan** [bazelbuild/bazel-gazelle#314]
Our setup is the following:

1. RepoA
2. RepoB

Both live in a private git instance (not Github), and do not implement go-get so we cannot use `dep` to vendor either. Both use bazel and have BUILD rules defined for all packages using gazelle.

Both RepoA and RepoB also have some vendored dependencies in Gopkg.toml (one of them is `k8s.io/apimachinery`).

RepoA defines a type with a field that is another type in `apimachinery` called `TypeMeta`. The idea is that RepoB creates the type (with `TypeMeta` as well).

What I want to do is vendor in RepoA in RepoB. So I did the following:

WORKSPACE (in repo B):

```
go_repository(
    name = "repo_a",
    commit = "aaaaaa",
    importpath = "repo_a.source.com/repo/a",
    remote = "sso://internal/repo/a",
    vcs = "git",
)
```

So, to install all my dependencies in RepoB, I do `dep ensure -v` and `bazel run //:gazelle`. Then, when I try to create the type, I get the following error:

```
cannot use "repo_b.source.com/repo/b/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta literal (type "repo_b.source.com/repo/b/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta) as type "repo_a.source.com/repo/a/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".TypeMeta in field value
```

Now yes, technically this error is correct. There is no way for the compiler to know that the two types that live in different paths are indeed the same. But what would help is if I was able to flatten out the vendors of the two dependencies defined by dep and bazel.

Is there a way to do this? If not, is this something that could be added in a future release?

**Comment by jayconrod** [comment]
So you can think of `go_repository` and repository rules in general as being analogous to checking a another repository into your `GOPATH`. Vendor directories are only visible within their parent directories, and `go build` won't let you share vendor directories across repositories. `gazelle` is meant to imitate `go build`, so it has the same semantics.

My usual recommendation would be to either vendor everything or use external repositories, but try to avoid using both. If you vendor the same package in multiple repositories, and types from that package are exposed in the public API, it's very easy to get compile and link-time errors due to conflicts.

Flattening the vendor directory in a single "main" repository where you do your builds may work, but you'll need `dep` or `go mod vendor` to be able to fetch other repositories. There are some [questions](https://stackoverflow.com/questions/27500861/whats-the-proper-way-to-go-get-a-private-repository) with answers on StackOverflow about how to get this to work with private repositories. I'm not sure if that works for you, but it looks pretty general.
