### ISSUE TITLE
Respect .bazelignore files

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#318]
These were introduced in Bazel 0.17.1. They allow directories to be excluded.

**Comment by Michaelhobo** [comment]
This was annoying me, and seemed pretty straightforward to add. Does this change seem to be going in the right direction? https://github.com/bazelbuild/bazel-gazelle/compare/master...Michaelhobo:bazelignore

I put my changes in Configurer.Configure, but I am not that familiar with this repo. Let me know if you think it should go somewhere else.

I'm still working on the change, but I wanted to quickly float it by the maintainers to make sure I'm not wildly off the mark.

**Comment by jayconrod** [comment]
If I understand `.bazelignore` correctly, it works similarly to the `# gazelle:exclude` directive but it can only appear in the repo root directory.

In that case, I think it makes sense to share logic with the exclude list in `walk.walkConfig`. If `walk.Configurer.Configure` is run with `rel == ""`, then it should read `.bazelignore` and add the lines to `wcCopy.excludes`.

**Comment by Michaelhobo** [comment]
Sorry for the lapse, I had trouble getting bazel-gazelle to build, and I put this aside for a while. I'm trying to wrap it up now. 

I filed my build issues here: https://github.com/bazelbuild/bazel-gazelle/issues/1020

**Comment by blico** [comment]
Reopening because #1022 had to be reverted due to the following issues: #1070, #1026

We should consider re-implementing the feature to be in parity with how Bazel reads the .bazelignore file. Meaning read in each line as paths relative to the repository root rather than supporting globs, etc. (https://github.com/bazelbuild/bazel-gazelle/pull/1071#issuecomment-868748998)
