### ISSUE TITLE
gazelle/go_repository should detect dependencies on header files specified via #cgo CFLAGS: -I${SRCDIR}/<path>

### ISSUE THREAD

**Issue by cstrahan** [bazelbuild/bazel-gazelle#348]
I have a project that uses something like so:

```
// #cgo CFLAGS: -I${SRCDIR}/internal/include -I${SRCDIR}/internal/libbacktrace
```

That project is included in the WORKSPACE of another project like so:

```python
go_repository(
    name = "com_github_cstrahan_cgosymbolizer",
    commit = "67837f878601260c69d94c2c5039a47f40bb233b",
    importpath = "github.com/cstrahan/cgosymbolizer",
)
```

Trying to compile the latter results in:

```
ERROR: /home/cstrahan/.cache/bazel/_bazel_cstrahan/0e3896d6d23d3761a1e0a1ef1f9e1eac/external/com_github_cstrahan_cgosymbolizer/BUILD.bazel:3:1: in cc_library rule @com_github_cstrahan_cgosymbolizer//:go_default_library.cgo_c_lib: The include path '/internal/libbacktrace' references a path outside of the execution root.
```

**Comment by jayconrod** [comment]
Marking as a bug since `${SRCDIR}/internal/include` clearly shouldn't expand to `/internal/include`.

Gazelle can't general rules for most Cgo code though that requires significant changes in flags though. It may be better to write build files for this repo by hand, then apply then as a patch with `git_repository` or `http_archive`.
