### ISSUE TITLE
update-repos -from_file=go.mod should handle replace with relative paths

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel-gazelle#407]
In update-repos, go.mod is copied to a temporary directory before being read. This is a problem when the mod file references relative paths, for example, when using the [replace directive](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive).

I think it is OK even if `go list -m` changes the go.mod file in some cases. This operation is run manually by the user, and is not part of a build.

The alternative could be to restore an original copy of the go.mod file.

**Comment by jayconrod** [comment]
I'm changing the issue title a bit: it sounds like the problem is that `update-repos` isn't handling relative paths, not specifically that `update-repos` uses a temp directory. 

I don't think `update-repos` should be able to modify the `go.mod` file, even temporarily. That would be pretty surprising behavior for me as a user (actually, I think go list's behavior is pretty surprising, but that's probably not going to change).

We might want to use `-mod=readonly` instead of making a temporary copy. Or we could adjust relative paths as part of the copy. In any case, `replace` directives with local paths should probably be imported as `local_repository` rules.

**Comment by siddharthab** [comment]
Thank you. Sounds good. Note that some of these relative paths could be resolve within the workspace itself, in which case things will be handled correctly by the prefix directive to gazelle.
