### ISSUE TITLE
Support language specific import prefixes

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#437]
Currently, the `# gazelle:prefix` directive applies to the `importpath` attribute for every library rule within its scope. It is not possible to define a prefix that will apply to a subset of library rules.

Our desire is to have multiple languages within a single directory, and for the library rules to have different `importpath` prefixes depending on the source language of the library. More concretely, if a go file and proto file reside in the same directory, the proto file's `go_proto_library` and `go_library` rules should have a different `importpath` prefix than the go file's `go_library` rule.

One solution is to add a prefix directive per language (e.g. `# gazelle: prefix_go`, `# gazelle: prefix_proto`). These directives would take priority over a `# gazelle:prefix` directive if also set.

**Comment by jayconrod** [comment]
`# gazelle:prefix` was introduced when Gazelle only supported Go and had very limited proto support. If it were added now, it would definitely be `# gazelle:go_prefix`. Maybe an alias should be added and the use of `# gazelle:prefix` should be discouraged. I doubt we'll ever remove it though, since it would break too many people.

Architecturally though, `# gazelle:prefix` is a language-specific directive. Each language extension can add support for new directives. They don't have to start with the language name, though that is good practice.

> More concretely, if a go file and proto file reside in the same directory, the proto file's go_proto_library and go_library rules should have a different importpath prefix than the go file's go_library rule.

I would lightly discourage this. Gazelle's charter, with respect to Go, is to translate the semantics of the Go command into Bazel build files. `go build` requires all the .go files in a directory to belong to the same package. `go_proto_library` doesn't quite translate of course, but it's analogous to checking in .pb.go files generated from the same .proto files.

**Comment by linzhp** [comment]
Another scenario we have is generating different sets of Go code using the same proto file, which is one of the use cases in #438. In a big repository, we have Go projects expecting Go code generated from a.proto using plugin P1, and other Go projects expecting Go code generated from the same a.proto but using plugin P2, which is incompatible with P1. P1 and P2 can be protoc-gen-go and protoc-gen-gogoslick, or v1 and v2 of the same plugin.

Since the generated Go code is incompatible with each other, we have to generate them as different Go packages. One way to separate these packages is to have different prefixes in their import paths. This requires Gazelle changes to:

* allow multiple prefixes in the same directory
* generate different build rules or build rules with different configurations according to prefixes available in the directory

@jayconrod What do you think?

**Comment by jayconrod** [comment]
@achew22 Sure, that would be the right way to migrate.

@linzhp This seems like a specialized use case. Gazelle relies heavily on convention, and I'd prefer not to support too many special cases like this to the default Go extension, as they add a lot of complexity. Since we'd be generating multiple `go_proto_library` rules, in addition to setting the `importpath` differently, we'd also need to consider different names, and we'd have to figure out how to associate any static `.go` files in the directory.

Maybe we can find another way to do this?

If you have a small number of protos that need this, the best option might be to use `# gazelle:proto disable`, then maintain the `proto_library` and `go_proto_library` rules by hand. Gazelle will still index `go_proto_library` rules and make them available for dependency resolution.

If you have more than a handful of protos like this, your best option is probably to fork the Go extension and add specialized rule generation code. You can use `gazelle_binary` to build a custom binary with your forked version instead of the default.

**Comment by blico** [comment]
The current plan is to create a "goproto" language extension that will use our specialized logic to generate `go_proto_library` and `go_library` rules from `proto_library` rules. 

Within our repo, .go files and .proto files never reside in the same directory. Meaning we could still use the default go extension for rule generation in our go only directories. We could also continue using the default go extension for resolving `go_proto_library` rules.

@jayconrod Do you see any pitfalls with this approach?

**Comment by jayconrod** [comment]
@blico Sounds good. Do you plan on using the default `go` extension in the same binary as `goproto`? You might get some conflicts if they're used together. If you run into problems, you could omit `go` from the `gazelle_binary` `languages` attribute, but import it from `goproto` and proxy calls through the `language.Language` interface in directories that only have `.go` files.
