### ISSUE TITLE
Missing Go imports

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#445]
When there is a import missing from the repo in both main source tree and `go_repository` rules, Gazelle will try to construct a external label for it. Part of the logic is to go out to the internet in order to determine the root of the possible external repo (https://github.com/bazelbuild/bazel-gazelle/blob/master/repo/remote.go#L214). This is very slow and the end result is simply an external label that's likely not buildable. In addition, the external label may not have the ideal path either. 

For example, if we have `example.com` as go_prefix in the repo, but some package depends on `example.com/foo/bar`, which is not in the repo or any existing `go_repository` rules. Gazelle should quickly report `unrecognized import "example.com/foo/bar"` and either skip that import or returning `//example.com/foo/bar:go_default_library`, instead of going out to the internet and trying to construct something like `@com_example_foo//bar:go_default_library`.

I am thinking about two solutions:

1. Adding a flag to Gazelle to turn off VCS lookup when it's trying to determine repo root.
2. Adding a logic before VCS before [this line](https://github.com/bazelbuild/bazel-gazelle/blob/master/repo/remote.go#L212) to see if the import has one of the `gazelle:prefix` directive as its prefix. If it does, return a `notFoundError`

@jayconrod What do you think?

**Comment by jayconrod** [comment]
There are a number of special cases for well-known code hosting sites. For example, we won't do external lookups for `golang.org` or `github.com`, since imports at those domains have predictable structure.

Gazelle will add repository roots from `go_repository` rules in WORKSPACE. You can add more of these with the `-known_import` flag. We won't do lookups for imports under these roots. There isn't an equivalent directive for this, but there probably should be. 

About solution 1, I think this would be fine, but we'd have to print a warning for imports that can't be resolved then.

About solution 2, the `repo` library should have minimal language-specific logic. It has a bunch of Go-specific stuff for historical reasons, but that should ideally be moved into `language/go` under some new `language.Language` method. In any case, because of the issues addressed by #409, it seems like we need to do external lookups even for import paths beneath the current prefix.

**Comment by linzhp** [comment]
`-known_import` works for me, as it doesn't lookup from the internet for the specified prefix. Thanks!
