### ISSUE TITLE
When an external dependency vendors another one of your external dependency

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/bazel-gazelle#465]
Let's say some code you write depends on import paths A and B, both of which are external repositories. Repository A also happens to vendor repository B. When you link your application you get warnings that the same importpath is presented to the linker.

I have found that a workaround to the linker warnings is to use the version of repository B that's vendor by A in my `deps`. For example, use `"@io_k8s_kubernetes//vendor/k8s.io/api/core/v1:go_default_library",` instead of `"@io_k8s_api//core/v1:go_default_library",` in your `deps`.

Is this a sensible approach? Are there better ways? If not, how would you prevent gazelle from using the external repository rather than the externally vendor repository?

**Comment by jayconrod** [comment]
I'd suggest one of two approaches:

**External repo approach:** Prevent everyone from using packages in A's vendor directory. You'll need to ensure the version of B you're using is compatible with A. This is what the Go command does in module mode: vendor directories outside the main module are ignored.

```
go_repository(
    name = "A",
    ...
    build_extra_args = ["-exclude=vendor"],
)
```

**Flat vendor approach:** Build a single, flat vendor directory and don't use `go_repository`. Vendoring tools like `dep` generally assume this is what you're doing. Even if you're not using Bazel, you can get the same compile, link, and run-time conflicts if you have A and B checked out into your GOPATH.

**Comment by mariusgrigoriu** [comment]
I was able to find success using the stuff that's vendored through the external repo. What's the downside of that approach? Seems that I don't have to deal with figuring out transitive dependencies since they already did that when the external repository vendored their dependencies.

I tried switching to a pure external repo approach as described above but haven't had enough time to make it work. (I'm not sure if I did the `-exclude=vendor` correctly because I was still getting conflicts between the external and the external vendored items.)

**Comment by jayconrod** [comment]
`go_repository` is pretty similar to checking out multiple projects into a `GOPATH` at specific versions. It works well on its own, but there are cases where it doesn't mix with vendoring.

Vendor directories are private to the projects that contain them. If they're not ignored or flattened, the same package may be built multiple times, potentially at different versions. This causes compile-time conflicts with types (types in multiple vendored packages are not compatible) and run-time conflicts when there's global mutable state.

gRPC and proto APIs in general are particularly dangerous here. gRPC has a global registry for services (global mutable state), and gRPC types frequently appear in clients' public APIs. `go_proto_library` won't work with vendored gRPC (since it implicitly depends on the external one), but even if you aren't using `go_proto_library`, having multiple copies of gRPC causes problems.

**Comment by mariusgrigoriu** [comment]
Thank you for elucidating.
