### ISSUE TITLE
Update github.com/bazelbuild/buildtools

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#489]
We want to pick up bazelbuild/buildtools#580 so that repository rules declared in macros have multi-line formatting.

Unfortunately, it looks like there have been some breaking changes since we last updated, so this will be a non-trivial operation.

**Comment by linzhp** [comment]
A related issue, not sure if we should address together with this one:

Right now, Gazelle is using //vendor/github.com/bazelbuild/buildtools. When a Gazelle extension tries to manipulate an object of buildtools from Gazelle, it will have to depend on `@bazel_gazelle//vendor/github.com/bazelbuild/buildtools`, instead of a regular `@com_github_bazelbuild_buildtools`. This sounds quite awkward. What's your thoughts?

**Comment by jayconrod** [comment]
@linzhp You're right, that's definitely a problem. I've opened #490 for that.
