### ISSUE TITLE
[Feature Request]: Support a "fix deps" mode

### ISSUE THREAD

**Issue by amineb3n** [bazelbuild/bazel-gazelle#496]
Hi,

Gazelle is a great tool with a lot of potential, thanks for that. Since it is young, it also has some area where it lacks flexibility: (the imposed go_default_library, not able to have different targets by folder, no granular visibility ...)

**Proposal:**
Support an additional mode "fix deps" which only scans **existing** build targets and regenerates the dependency set for them. This would allow us to still have the flexibility to organize our build targets however we want while automating the most tedious part (figuring out the dependencies).

Currently, running the update operation will erase any customization made on the generated build target. That is a deal breaker for me. With the proposal above, I could generate the initial set of build files, edit them, then keep the deps up to date when code changes (without losing my edits).

Wdyt ?

**Comment by jayconrod** [comment]
Could you give an example of the workflow you'd like? I'm not sure I understand the request.

You can add `# keep` comments on individual values, attributes, or entire rules to prevent Gazelle from modifying them. Maybe that's enough to preserve edits? It depends on what kind of edits you're making though.

There currently isn't a way to prevent Gazelle from generating certain rules (e.g., not generating tests). Maybe there should be.

In general though, I'm pretty hesitant to add too much more flexibility. The job of the Go extension is to map conventions from the Go command to Bazel build files. Deviating from that causes a lot of issues and makes Gazelle harder to support.

**Comment by amineb3n** [comment]
Thanks for the quick response. A couple of examples:
1- Multiple go_library within the same package (folder)
2- Custom names per target.
3- Sometimes, the visibility is neither public nor private but rather a list of other packages. 

My ideal flow would be:
1- Generate build targets for new files.
2- [optional] edit them if needs be. (An example would be to split the go_library generated and rename them)
3- While modifying go files which are already in existing build targets, i would want the deps of these existing build target to be updated (and not bigger changes where the tool regenerates/override other attribute).

Also i don't think this FR breaks away from go convention and it shouldn't make gazelle harder to support. This (resolving the set of dependencies of a go target) is already a problem that gazelle knows how to solve. It is a subset of the work needed for generating go targets.

**Comment by jayconrod** [comment]
Sorry, I'm going to close this.

I don't think there's anything wrong with this workflow (indeed, what you describe is similar to how Google manages Go source code), but it's not consistent with the general mission of Gazelle's Go extension, which is to map `go build` conventions to Bazel. Having strong conventions makes repositories easier to understand and tools like Gazelle easier to maintain.

You might consider forking or replacing Gazelle's Go extension in your own project. There's some information on how to do this in [Extending Gazelle](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.rst). bazelbuild/rules_sass#75 (not merged yet) is an example of a new extension outside of Gazelle.

------

About the examples you were describing:

1. This is the big part that differs from Go convention. The Go command forbids multiple packages in the same directory.
2. This will only work if libraries are indexed for dependency resolution. While this is true by default within a repository, it won't work for `go_repository` or with autogazelle. Large repositories may want to disable indexing anyway, since it's expensive.
3. This should actually work without modification. Gazelle won't update existing `visibility` attributes.
