### ISSUE TITLE
go_repository: add GOPROXY support

### ISSUE THREAD

**Issue by TennyZhuang** [bazelbuild/bazel-gazelle#503]
https://tip.golang.org/cmd/go/#hdr-Module_proxy_protocol

**Comment by jayconrod** [comment]
`go_repository` already downloads modules with `go mod download` and respects `GOPROXY` on `master`. Is there something missing?

**Comment by TennyZhuang** [comment]
Hello, how can I pass the GOPROXY environment to go_repository? I tried
something like action_env command line flag and it seems not work. Is there
any example  to use GOPROXY? And is it possible to specify GOPROXY directly
in WORKSPACE?

Sorry for the easy question, but I really not find the correct solution.

Jay Conrod <notifications@github.com>于2019年4月22日 周一22:40写道：

**Comment by jayconrod** [comment]
You should be able to just set `GOPROXY` in your environment; no other special flags needed. Make sure you're using Gazelle at `master`: I don't think `GOPROXY` was supported in the most recently released version. Also make sure your `go_repository` rules are in module mode (they should have `version` and `sum` attributes instead of `commit` or `urls`).

Just as a quick test, if I have a rule like this:

```
go_repository(
    name = "com_github_pkg_errors",
    importpath = "github.com/pkg/errors",
    sum = "h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=",
    version = "v0.8.1",
)
```

And then I run:

```
$ GOPROXY=off bazel fetch @com_github_pkg_errors//:go_default_library
Loading: 0 packages loaded
ERROR: no such package '@com_github_pkg_errors//': failed to fetch com_github_pkg_errors: fetch_repo: module lookup disabled by GOPROXY=off
Loading: 0 packages loaded
Loading: 0 packages loaded
```

That shows the `GOPROXY` environment variable is passed through to `fetch_repo`, the tool that downloads repositories.

**Comment by TennyZhuang** [comment]
Thanks. Another question is that is it possible to add a argument with update-repos to generate the version but not the commit?

**Comment by jayconrod** [comment]
That's something I've been meaning to do. I've opened #505 to track that.

**Comment by TennyZhuang** [comment]
It's very excited, can't wait to see this feature released.
Thanks.
