### ISSUE TITLE
rule: generate dict expressions from maps

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-gazelle#511]
First of all thanks for the great work, even if not everything is clear to me yet it was pretty straightforward to set some auto-generation up.

Anyway, I am writing a plugin for js and want to set a `string_dict` attribute. I assumed `rule.SetAttr("attr", map[string]string{"key": "val"})` would do the trick but that gets converted into a select statement. It is also mentioned like that in the docs: https://github.com/bazelbuild/bazel-gazelle/blob/master/rule/value.go#L45

What would be the preferred way to add this functionality? I would assume reflect alone is not enough anymore. Maybe we need a second parameter for the `SetAttr` method?

**Comment by jayconrod** [comment]
I can think of two approaches: the Right Way that involves breaking backward compatibility, and the Quick Way which doesn't.

The Quick Way: add `type StringDict map[string]string` to `rule`. In `rule.ExprFromValue`, use `rv.Type().Name()` to distinguish `StringDict` (which would now generate a dict expression) from other map types (which would still generate `select` calls).

The Right Way: add `type SelectStringList map[string][]string` to `rule`. Same deal as above, except `select` would be the special case instead of the default. The map fields of `PlatformStrings` would need to change to `SelectStringList`. This would be an incompatible change, so `language/go` might need some fixes to handle that. I'm generally opposed to incompatible API changes, but this is probably the right thing to do. Gazelle language extensions are young enough that I'd be a little surprised if anyone is emitting `select` expressions at this time, so maybe it's okay. We're not at v1.0.0 quite yet.

I'd accept a PR for either approach. They're not mutually exclusive, so we could do the Quick Way first and the Right Way later.
