### ISSUE TITLE
What is the new replaced method for the overlay property of http_archive and git_repository

### ISSUE THREAD

**Issue by weixiao-huang** [bazelbuild/bazel-gazelle#533]
In bazel-gazelle's `internal/overlay_repository.bzl`, it defines an `overlay` property for http_archive and git_repository, which is useful for external go repositories which needs to define BUILD.bazel by ourselves.

However, gazelle informs us that
```
overlay_repository.bzl:42:5: git_repository is deprecated. Use git_repository from @bazel_tools//tools/build_defs/repo:git.bzl instead.
overlay_repository.bzl:16:5: http_archive is deprecated. Use http_archive from @bazel_tools//tools/build_defs/repo:http.bzl instead.
```
But the `git_repository/http_archive` in `@bazel_tools//tools/build_defs/repo:http.bzl` does not have an `overlay` property. Although it provides the `build_file` property, this property can only assign one BUILD.bazel file, which is not as flexible as the `overlay` property by using a map to assign multiple BUILD.bazel files. So I wonder what is the new replace method for the overlay property of http_archive and git_repository?

**Comment by jayconrod** [comment]
The Bazel `git_repository` and `http_archive` both support several attributes for patching: `patches`, `patch_args`, `patch_tool`, and `patch_cmds`. These turn out to be a lot more useful. Patches can be much smaller and can replace a few lines instead of an entire file. They can also delete files, which overlays can't do. [`go_rules_dependencies`](https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl) switched to using these, and I'm pretty happy with the change. It's been much more convenient.

Just for reference, `go_repository` supports the same patch attributes. You can use that to adjust the build files that Gazelle generates, or modify other files in the repository.
