### ISSUE TITLE
Generate a filegroup named go_default_sources

### ISSUE THREAD

**Issue by TennyZhuang** [bazelbuild/bazel-gazelle#540]
It can be implemented easily, even just using glob.

It will be very useful while add some linting rules.

**Comment by jayconrod** [comment]
Linting rules should use the [`GoSource`](https://github.com/bazelbuild/rules_go/blob/master/go/providers.rst#gosource) provider instead of filegroups. [`go_path`](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#go-path) may also be useful.

Can your problem be solved by one of those?

**Comment by TennyZhuang** [comment]
It seems that
https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#library_to_source
is exactly what i want. I will try it, thanks!

Jay Conrod <notifications@github.com>于2019年6月6日 周四22:29写道：
