### ISSUE TITLE
FYI - Gazelle for JS

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#546]
Just wanted to share that I've successfully added a `js` language module to Gazelle to produce closure_js_library targets. I don't expect you'd want to merge it and take on the maintenance burden, but I figure you might find it interesting and maybe someone else finds it helpful.
https://github.com/bazelbuild/bazel-gazelle/compare/master...robfig:js

**Comment by achew22** [comment]
@robfig, this might be a thing that `rules_closure` is interested in merging. I wrote something like this that we're trying to get merged into [`rules_sass`](https://github.com/bazelbuild/rules_sass/pull/75). Have you considered starting a discussion with the rules_closure group to have it live in there?

**Comment by robfig** [comment]
Very interesting.. I'll open an issue with them. If I understand correctly, you've actually checked in the language module to the rules_sass repo, yet you can still it up to build a gazelle with that included? Very cool.

**Comment by achew22** [comment]
That's correct. The goal was to have the plugin local to the `rules_*` that defines it. That way when you update `rules_*` it will update the plugin and all your `BUILD` files will be updated magically :smile:

**Comment by Globegitter** [comment]
Ah nice to see more plugins cropping up - I added support for js/ts with rules_nodejs: https://github.com/ecosia/bazel_rules_nodejs_contrib#build-file-generation

**Comment by Globegitter** [comment]
I wonder also if it could be interesting to keep a list of plugins here also to make it easier for others to find them.

**Comment by jayconrod** [comment]
@robfig This is cool. Thank you for sharing this! As @achew22 suggested, would you consider sharing this with the `rules_closure` folks in case they'd be interested in merging it?

I think ideally, each rule set would have a Gazelle extension. I think those probably belong in rule repositories rather than in Gazelle itself, since the rule set authors are the most knowledgable on how their rules should be generated and used. I'm happy to review PRs for Gazelle API usage and Go readability, but I don't know enough about TypeScript or SASS for example to contribute anything substantive there.

@Globegitter Thanks for linking that extension! Collecting a list of extensions is a good idea. I've opened #554 for this.

**Comment by robfig** [comment]
Sounds good, I opened https://github.com/bazelbuild/rules_closure/issues/394 to gauge their interest. If they don't want to maintain it, I'll just host it in a standalone repo. I'll open a PR to add it to the list you started once it's in shape. Thanks!
