### ISSUE TITLE
gazelle could not merge expression

### ISSUE THREAD

**Issue by dfang** [bazelbuild/bazel-gazelle#551]
BUILD.bazel
```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    command = "fix",
    prefix = "github.com/dfang/wechat-work-go",
)

go_library(
    name = "go_default_library",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    importpath = "github.com/dfang/wechat-work-go",
    visibility = ["//visibility:public"],
    deps = [
        "//models:go_default_library",
        "@in_gopkg_resty_v1//:go_default_library",
    ],
)
```

when i run `bazel run //:gazelle`, got 

```
INFO: Analyzed target //:gazelle (2 packages loaded, 110 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 1.343s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: /Users/mj/src/OSS/wechat-work-go/BUILD.bazel:12.12-15.6: could not merge expression
gazelle: /Users/mj/src/OSS/wechat-work-go/BUILD.bazel:26.12-28.6: could not merge expression
```

gazelle does not support glob from bazel yet ?

**Comment by jayconrod** [comment]
Working as intended.

When Gazelle runs in a directory, it generates a list of rules, then attempts to merge them with the existing list of rules by attribute and by expression.

For mergeable attributes like `srcs`, Gazelle merges expressions by dropping values from lists in the existing expression unless they are marked by a `# keep` comment or also appear in the generated expression. Then new values are added from the generated expression.

Merging requires that the existing expression is something Gazelle understands: a string, or a list of strings, or a sequence of `select` expressions following a certain form. `glob` is not something we can easily deal with, and it isn't supported.

If you need to manage these attributes directly, you can mark the whole attribute or even the whole rule with a `# keep` comment to prevent Gazelle from updating it. Otherwise, I'd suggest removing the attribute and re-running Gazelle to fill it in with a list of sources.
