### ISSUE TITLE
patches in go_repository are applied after BUILD file generation

### ISSUE THREAD

**Issue by dududko** [bazelbuild/bazel-gazelle#569]
For one of my project's external dependency I need to apply a `patch` which adds additional dependencies to a repo by introducing new import to a golang file. But since `patches` are applied after the `BUILD.bazel` files are generated the new dependency is not listed in the `deps` list. This result in the unsuccessful build. 

Do you consider to change the implementation of a `go_repository` rule so that patch will be applied after fetching step and before generation step ?

**Comment by jayconrod** [comment]
Most patches need to be applied after build files are generated because they add extra targets or fix problems in build files. It might be useful to apply some patches before build files are generated, but I'd like to keep the feature set minimal. In this situation, can your patch add the import *and* add the dep to the build file?

**Comment by dududko** [comment]
Yes, I can include this to my patch. Thank you for a fast reply!
