### ISSUE TITLE
Protobuf support for IDE.

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/bazel-gazelle#575]
I am able to build my protobuf files fine, the output is great but my IDE (Goland) fails to pick it up and give me autocomplete on it.

How are people getting around this?

**Comment by LanceEa** [comment]
@bweston92 
See issue [512](https://github.com/bazelbuild/rules_go/issues/512) in the rules_go repo & the following [comment]( https://github.com/bazelbuild/rules_go/issues/2111#issuecomment-506543086). The work discussed in these issues will allow for IDE support.

In the meantime, the way I do it to get autocomplete is to manually run the protobuf compiler so that it creates `bp.go` files. Anytime you change a proto file you will need to manually re-run the protoc. Bazel will still use the protoc to create them in the sandbox directory for building your code and these manually created files are purely for IDE support. Hope that helps!

**Comment by bweston92** [comment]
Thanks

**Comment by achew22** [comment]
@bweston92 I've had a lot of luck with [this script](https://gist.githubusercontent.com/kalbasit/3c9607333f5f3c794d2bd96114184301/raw/07c878cca4913a9592462866c66da32179993a1f/proto.sh) creating symlinks in my real project dirs to the generated files. The good thing about that is you don't ever have to update them, the bad thing is that you don't have them until  you `bazel build` and run `linkify.sh` the first time.

**Comment by bweston92** [comment]
Thanks @achew22

**Comment by nikunjy** [comment]
I wrote a bazel module that you can import (it is a hack but it works well) https://github.com/nikunjy/golink
