### ISSUE TITLE
External dependency resolution slow without gazelle:repository_macro directive

### ISSUE THREAD

**Issue by asv** [bazelbuild/bazel-gazelle#607]
`bazel run //: gazelle` takes a lot of time in our project workspace.

My current system:
CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Memory: 16Gb
SSD

```shell
$ time bazel run //:gazelle
INFO: Analyzed target //:gazelle (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.288s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

real	0m17,891s
user	0m3,471s
sys	0m1,259s
```

Sequential run also takes a long time (does gazelle not cache results?).
I'm attach result of `bazel run --profile //:gazelle` [prof.txt](https://github.com/bazelbuild/bazel-gazelle/files/3455438/prof.txt).

**Comment by jayconrod** [comment]
Anything specific that triggers this? Do you have an example where Gazelle is particularly slow?

**Comment by asv** [comment]
I compiled version 0.17, it works much faster:
```sh
$ time ./gazelle update -go_prefix project/prefix

real    0m0,562s
user    0m0,087s
sys     0m0,025s
```

**Comment by asv** [comment]
I will try to create some repro repo, but it is not sure when I'll find time...

**Comment by asv** [comment]
git bisect pointed to `dee3700d6d18ca667ef5785c822721dd0ae159ef is the first bad commit`

**Comment by asv** [comment]
repro repo: https://github.com/asv/slow_gazelle_018_repro

gazelle 0.18.1:
```
$ time gazelle update -go_prefix slow_gazelle
                                                                                                                                                                               
real    0m9,992s                                                                                                                                                                                                     user    0m1,208s
sys     0m0,367s 
```

gazelle 0.17.0:
```
$ time ./gazelle update -go_prefix slow_gazelle

real    0m0,005s
user    0m0,006s
sys     0m0,000s
```

**Comment by jayconrod** [comment]
`dee3700` explains the difference.

Previously when Gazelle resolved an import path outside of the current repository, it needed to find what part of the path corresponded to the repo name. There were special cases for `github.com`, `golang.org`, `gopkg.in`, and a few other domains, which means that it wasn't necessary to go out to the network most of the time.

For module mode, which is now much more common, we need to figure out the part of the path that corresponds to the module root, since that's what determines the repo rule name. Because a module need not be declared at the root of the repository, we always go out to the network to find this.

If `go_repository` rules are declared in a place that Gazelle can find, it should be relatively rare that we actually need to do this. If you add a `# gazelle:repository_macro` directive in WORKSPACE that points to your macro (`# gazelle:repository_macro godeps.bzl%go_deps` should do it), Gazelle will index those `go_repository` rules and will not go out to the network for those paths. We should document that a bit better.

**Comment by asv** [comment]
Thank! It works!
