### ISSUE TITLE
When an external library depends on an internal package of another dependency, Gazelle creates a rule that doesn't compile.

### ISSUE THREAD

**Issue by draftcode** [bazelbuild/bazel-gazelle#619]
# What version of gazelle are you using?

0.18.1

### What version of rules_go are you using?

0.19.1

### What version of Bazel are you using?

0.28.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux AMD64

### What did you do?

Create a workspace with the following files.

https://gist.github.com/draftcode/8b60bb587c3739d1a64bd4f61343e8b9

This is basically creating a minimum workspace that depends on cloud.google.com/go/logging.

Build with `bazel build ...`.

### What did you expect to see?

Compile without an error.

### What did you see instead?

Build failure like this:

```
ERROR: $HOME/.cache/bazel/_bazel_masayasuzuki/15220e3a80e87c9c56aecefb5d0ff5e7/external/com_google_cloud_go_logging/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_logging//:go_default_library: target '@com_google_cloud_go//internal/version:go_default_library' is not visible from target '@com_google_cloud_go_logging//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//:go_default_library' failed; build aborted: Analysis of target '@com_google_cloud_go_logging//:go_default_library' failed; build aborted
INFO: Elapsed time: 0.161s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
zsh: exit 1     bazel build ...
```

---

It seems cloud.google.com/go/logging depends on cloud.google.com/go's internal package (https://github.com/googleapis/google-cloud-go/blob/master/logging/logging.go#L43). Because Gazelle uses a heuristics on creating a visibility, the internal package is not visible from cloud.google.com/go/logging.

Perhaps Gazelle can generate a package_group that includes all external libraries and use that to let external libraries depend on other external libraries. This way, the code in the workspace still cannot depend on the internal packages of external libraries, but the external libraries can depend on other external libraries' internal packages.

**Comment by jayconrod** [comment]
Oh, fun, cross-module use of `internal` directories.

For now, I'd suggest working around this with `patches`.

1. Copy `$(bazel info output_base)/external/com_google_cloud_go)` to a directory `a`.
2. `cp -r a b`
3. Modify `visibility` attributes in `b` as needed. [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) is useful for build edits.
4. `diff -urN a b >com_google_cloud_go-visibility.patch`
5. Use the patch in the `go_repository` rule:

```
go_repository(
    name = "com_google_cloud_go",
    ...
    patches = ["com_google_cloud_go-visibility.patch"],
    patch_args = ["-p1"],
)
```

---

I'm not sure what the proper solution to this is. The problem with defining a `package_group` is that we don't have an exhaustive list of submodules. We download modules using `go mod download` (ideally using a proxy), so we just get a .zip that doesn't include the submodules.

Maybe we could add a `# gazelle:go_submodules` directive that could list them. When we import `go_repository` rules using `update-repos -from_file=go.mod`, it could add those directives to `go_repository` rules that need them.

**Comment by amacneil** [comment]
For now it's possible to work around this issue by reverting to `cloud.google.com/go v0.44.1` or earlier.

FYI @jadekler about this issue. Perhaps it is possible to avoid cross-module imports of internal packages in the google cloud go libraries?

**Comment by jadekler** [comment]
Hello! Trying to get caught up on this issue. Is this a problem with the bazel build process that handles `internal/` folders in "higher level but same repository" modules (should we call them parent modules...?) differently than the `go` command? If so, seems like the solution should be to make bazel build process work the same as the `go` command.

(I think this is what Jay is alluding to by adding `gazelle:go_submodules`?)

Not super intelligent about any of this bazel stuff, though, sorry. It does ultimately seem not-a-good-solution to expect independent modules to conform to bazel module requirements rather than go module requirements, though.

**Comment by jayconrod** [comment]
The issue is about mapping Go visibility rules to Bazel. When Gazelle enters an `internal` directory, it generates rules with `visibility = ["//foo/internal:__subpackages__"]`.

That's fine when we're thinking about repositories containing multiple modules, but `go_repository` in module mode downloads and extracts a module zip (not containing submodules), not a repository. Submodules are a different workspace as far as Bazel is concerned, so packages in submodules won't have access to internal packages in a parent module, according to these visibility declarations.

I think the command `gazelle update-repos -from_file=go.mod` could be made smart enough to handle this. I'll try and come up with a fix this week. `cloud.google.com/go` ought to work with minimal configuration.

> Perhaps it is possible to avoid cross-module imports of internal packages in the google cloud go libraries?

I think this is good advice in general, though I don't know enough about how these internal packages are used to say if that applies here.

**Comment by amacneil** [comment]
@jadekler correct, the problem seems to be that gazelle doesn't support imports from `internal` folders in "parent" modules. According to the [Go modules FAQ](https://github.com/golang/go/wiki/Modules#can-a-module-depend-on-an-internal-in-another) this is supported behavior:

> Packages in one module are allowed to import internal packages from another module as long as they share the same path prefix up to the internal/ path component.

This does seem like a bit of an edge case - tbh I'm surprised that go modules don't explicitly disallow imports of internal paths from "parent" modules (which are effectively entirely separate modules). However, given that `go` supports this today, Gazelle should definitely support it too.

@jayconrod thank you for taking a look at this! Appreciate the responsiveness.

**Comment by jayconrod** [comment]
Reopening because I just thought of a way the fix could be simpler (right after merging of course).

The `build_submodule` attribute probably isn't necessary.

**Comment by bamnet** [comment]
Looking forward to seeing this ship :+1: 

I spent a while struggling to get `bazel run //:gazelle -- update-repos -from_file=go.mod` to produce a working build because I had dependency on `cloud.google.com/go/bigquery`.  The simplest fix ended up being to just swap in:

```
git_repository(
    name = "bazel_gazelle",
    commit = "fe0ec4f9369d78ff80a1f3f519c63d715f6cbd75",
    remote = "https://github.com/bazelbuild/bazel-gazelle",
    shallow_since = "1569779917 -0400",
)
```

This resolved a bunch of gax-go dependency errors and visibility problems I had after that.

**Comment by flokli** [comment]
This still seems to fail for `@com_google_cloud_go_storage`:
```
ERROR: /home/flokli/.cache/bazel/_bazel_flokli/8dadcab6b13a52152fcdd41393844c95/external/com_google_cloud_go_storage/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_storage//:go_default_library: target '@com_google_cloud_go//internal:go_default_library' is not visible from target '@com_google_cloud_go_storage//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/flokli/.cache/bazel/_bazel_flokli/8dadcab6b13a52152fcdd41393844c95/external/com_google_cloud_go_storage/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_storage//:go_default_library: target '@com_google_cloud_go//internal/optional:go_default_library' is not visible from target '@com_google_cloud_go_storage//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/flokli/.cache/bazel/_bazel_flokli/8dadcab6b13a52152fcdd41393844c95/external/com_google_cloud_go_storage/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_storage//:go_default_library: target '@com_google_cloud_go//internal/trace:go_default_library' is not visible from target '@com_google_cloud_go_storage//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/flokli/.cache/bazel/_bazel_flokli/8dadcab6b13a52152fcdd41393844c95/external/com_google_cloud_go_storage/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_storage//:go_default_library: target '@com_google_cloud_go//internal/version:go_default_library' is not visible from target '@com_google_cloud_go_storage//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//foo/bar/baze/server:server' failed; build aborted: Analysis of target '@com_google_cloud_go_storage//:go_default_library' failed; build aborted
```

**Comment by jayconrod** [comment]
@flokli Please open a new issue with enough info to reproduce.

**Comment by flokli** [comment]
Will do, thanks!

**Comment by flokli** [comment]
Opened at https://github.com/bazelbuild/bazel-gazelle/issues/680.
