### ISSUE TITLE
Please tag 0.18.2

### ISSUE THREAD

**Issue by fejta** [bazelbuild/bazel-gazelle#640]
Looking at the commit tags, it looks like there is only a 0.18.1. The 0.18.2 is present in the releases (and releases tags??) but go mod does not appear to be able to download 0.18.2

**Comment by jayconrod** [comment]
Done, sorry this should have been tagged with a `v` prefix as part of the last release (Go modules requires that). I've pushed copies of all the tags with a `v` prefix now.

Due to caching, this won't be visible on proxy.golang.org for a little while due to caching, but `GOPROXY=direct go list -m -versions github.com/bazelbuild/bazel-gazelle` shows all the versions now.
