### ISSUE TITLE
Gazelle can add line breaks to globs

### ISSUE THREAD

**Issue by fejta** [bazelbuild/bazel-gazelle#644]
kazel and gazelle have different opinions about how to format the following. Gazelle wants:

```python
 filegroup(
     name = "package-srcs",
     srcs = glob(
         ["**"],
         exclude = [
             "bazel-*/**",
             ".git/**",
         ],
     ),
     tags = ["automanaged"],
     visibility = ["//visibility:private"],
```

whereas kazel wants:
```python
 filegroup(
     name = "package-srcs",
     srcs = glob(["**"], exclude=["bazel-*/**", ".git/**"]),
     tags = ["automanaged"],
     visibility = ["//visibility:private"],
```

I suspect this has something to do with:
```console
~/src/gh/repo-infra/bazel-repo-infra/external/com_github_bazelbuild_bazel_gazelle$ grep -R Force .
./rule/expr.go:			e.ForceMultiLine = true
./rule/expr.go:			e.List[0].(*bzl.DictExpr).ForceMultiLine = true
./rule/merge.go:		ForceMultiLine: src.ForceMultiLine || dst.ForceMultiLine || keepComment,
./rule/merge.go:	return &bzl.DictExpr{List: mergedEntries, ForceMultiLine: true}, nil
./rule/rule.go:				ForceCompact: true,
./rule/rule.go:			loadStmt.ForceCompact = false
./rule/rule.go:		call.ForceMultiLine = true
./rule/value.go:				l.ForceMultiLine = true
./rule/value.go:			List: []bzl.Expr{&bzl.DictExpr{List: args, ForceMultiLine: true}},
./rule/value.go:					list.ForceMultiLine = true
```

Looks like the [relevant kazel logic](https://github.com/kubernetes/repo-infra/blob/967e39a37fb93640a37e272949ddf92a8c96f230/cmd/kazel/kazel.go#L349-L354) is:
```golang
func writeFile(path string, f *build.File, boilerplate []byte, exists, dryRun bool) (bool, error) {
	var info build.RewriteInfo
	build.Rewrite(f, &info)
	var out []byte
	out = append(out, boilerplate...)
	out = append(out, build.Format(f)...)
```

Both utils are built with `github.com/bazelbuild/buildtools v0.0.0-20190731111112-f720930ceb60`

My vim editor actually adds the line breaks, so perhaps this current behavior is correct.

**Comment by jayconrod** [comment]
Sorry I haven't had a chance to look at this until now. I think this behavior comes from how `github.com/bazelbuild/buildtools/build` formats ASTs. Gazelle isn't explicitly asking for this (especially in rules that Gazelle didn't update), it just seems to be part of what `build.File.Format` does.

As an experiment, I pasted this into a BUILD.bazel file:

```
glob(["**"], exclude = ["bazel-*/**", ".git/**"])
```

then ran `buildifier BUILD.bazel`. It rewrites the file as:

```
glob(
    ["**"],
    exclude = [
        "bazel-*/**",
        ".git/**",
    ],
)
```

(I note this when I save a file in emacs too; I have `buildifier` set as a save hook).

I'll close this because I don't think Gazelle should change what it's doing (nor can I easily change how the files are formatted). How is kazel formatting these files? If it's also using `github.com/bazelbuild/buildtools/build`, I would expect it to add line breaks, too.
