### ISSUE TITLE
how to avoid import one package with different go_repository name and importpath

### ISSUE THREAD

**Issue by moruowait** [bazelbuild/bazel-gazelle#675]
### What version of gazelle are you using?

0.19.0

### What version of rules_go are you using?

0.19.4

### What version of Bazel are you using?

1.0.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

Darwin

### What did you do?

I use `github.com/google/go-github` library to access GitHub, so I declared a repository in WORKSAPCE:

```
go_repository(
    name = "com_github_google_go_github",
    importpath = "github.com/google/go-github",
    urls = ["https://github.com/google/go-github/archive/v28.1.1.tar.gz"],
    strip_prefix = "go-github-28.1.1",
)
``` 

And I also want to use `github.com/bradleyfalzon/ghinstallation` which has a dependency `github.com/google/go-github/v28`, so I add repositories in WORKSAPCE:

```
go_repository(
    name = "com_github_bradleyfalzon_ghinstallation",
    importpath = "github.com/bradleyfalzon/ghinstallation",
    urls = ["https://github.com/bradleyfalzon/ghinstallation/archive/v1.0.0.tar.gz"],
    strip_prefix = "ghinstallation-1.0.0",
)

# transitive dependency of com_github_bradleyfalzon_ghinstallation
go_repository(
    name = "com_github_google_go_github_v28",
    importpath = "github.com/google/go-github/v28",
    urls = ["https://github.com/google/go-github/archive/v28.1.1.tar.gz"],
    strip_prefix = "go-github-28.1.1",
)
```

`com_github_google_go_github` and `com_github_google_go_github_v28` are the same package.

I use `com_github_google_go_github` in my code, and the thirdpary `com_github_bradleyfalzon_ghinstallation` use `com_github_google_go_github_v28` in their code. It will build fail due to wrong type assignment.

Then, I set `# gazelle:repository go_repository name=com_github_google_go_github importpath=github.com/google/go-github/v28` to WORKSAPCE, but it will cause `com_github_bradleyfalzon_ghinstallation` missing dependency of `com_github_google_go_github_v28`.

I do not want to use `com_github_google_go_github_v28` in my code, is there a way to change the thirdparty to use `com_github_google_go_github` instead?

**Comment by jayconrod** [comment]
The most common way to use `go_repository` is to download one module per `go_repository` rule. In module mode, you'd set `version` and `sum` instead of `urls` and `strip_prefix`.

Since `github.com/bradleyfalzon/ghinstallation` has a `go.mod` file, Gazelle will follow module conventions, so dependencies with `com_github_google_go_github_v28` are correct. You can have multiple major versions of a module, and they need to have distinct names.

> I do not want to use com_github_google_go_github_v28 in my code, is there a way to change the thirdparty to use com_github_google_go_github instead?

Patching is the general solution for changing upstream dependencies. See details in the [`go_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst) documentation. You could either remove the `go.mod` file or provide your own build files (and use `http_archive` instead of `go_repository`).
