### ISSUE TITLE
Feature Request: Sorting repository rules

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#696]
Current `gazelle update-repos` appends new repository rules to the end of the WORKSPACE file or macro. This approach can easily leads to merge conflict in a large repository with many developers, as they are trying to add different external dependencies to the end of the current list.

To reduce the chance of merge conflict, we should sort repository rules in some way, e.g., by name. New repo rules are likely to be inserted at different location of the current list.

There are a few design questions related to this:

## Should we sort both WORKSPACE file and macros?

I prefer sorting macros only, because WORSPACE file often includes rules (http_archive, http_file) that are manually maintained. People may prefer to keep some repo rules at the top because of their importance, e.g., loading rules_go, gazelle, setting up go toolchain. However, I am open to have a switch to turn on the sorting of WORSPACE file, but I definitely want to be able to turn it off for our repo.

## If the existing repo rules are not sorted, should we sort them during next `update-repos` run?

We probably should. As @jayconrod suggested, we can add a `rule.File.Sort` to sort and sync a file. This is related to #694 except this feature request will sort all rules, not just newly imported rules.

@jayconrod Any concerns?

**Comment by jayconrod** [comment]
I agree we should not attempt to sort `WORKSPACE`. There's often some complicated interdependence between repositories declared there, so the order is important.

Sorting rules declared in macros seems less obvious, but Gazelle probably (already) can't update macros where the order is important, so I think it makes sense to always sort. If it turns out to be a problem, we can add a directive or something later to control it.

Making this work will be a little tricky. Inserted statements in the `rule` package have an index associated with them (in the embedded `stmt` struct). They aren't actually inserted until `rule.File.Sync` is called. I think we should have a `rule.File.Sort` method that calls `Sync` first (to handle pending insertions and deletions), then sorts `rule.File.Loads` and `rule.File.Rules`. Each `Swap` operation (in [`sort.Interface`](https://pkg.go.dev/sort?tab=doc#Interface)) should swap not only the high-level loads and rules but also the underlying `bzl.Expr` and indexes.

For the sort order, I think sorting loads by module label and sorting rules by name is good enough. I don't expect we'll need custom sort functions, and we could always add a `SortBy` method if it turns out we do.

Sorting module labels may require some new code though. They should be sorted in the same order that buildifier sorts them (see [`build.SortStringList`](https://pkg.go.dev/github.com/bazelbuild/buildtools/build?tab=doc#SortStringList)), but that code is not directly usable. But see the comment on [`stringSortKey`](https://github.com/bazelbuild/buildtools/blob/406053e3dd00/build/rewrite.go#L601) in particular.

**Comment by linzhp** [comment]
As you have noticed, sorting existing repository rules in macros gets tricky, requiring pretty widespread changes. You may want to reconsider the approach of #693 (with your comments of the implementation addressed), which is much simpler. 

1. If existing repo rules are sorted, they will continue to be sorted
2. If existing rules are not sorted, they will continue to be unsorted with their current location preserved
3. If people wants to sort existing rules, they can remove all repo rules from a macro and let Gazelle re-populate them. This is the way we maintain the order of the rules now. We have a bash script to remove all repo rules before running `gazelle update-repos`. With #693, we don't have to run that bash script anymore.

**Comment by linzhp** [comment]
@jayconrod Do you still prefer the more comprehensive approach of sorting all existing rules, or is it OK to go with the more moderate approach of #693? Either way works for us, though the more comprehensive way requires more changes.

**Comment by jayconrod** [comment]
Sorry for the slow response (I've been occupied with 1.14 release blockers and 1.15 planning).

Not a strong opinion, but I lean toward sorting rules in dependency macros unconditionally. There isn't any semantic order to these rules, and they're more manageable when they're sorted. We already sort `srcs` and `deps` lists. We don't sort targets in build files, but they tend to have structural relationships more meaningful than names.

The alternative would be to test whether the list is sorted and insert new rules in order if so and at the end if not (in order). That's less disruptive, but I think it's better to avoid the complication.

**Comment by linzhp** [comment]
Testing whether the list is sorted sounds a good idea. The other way I am thinking is to insert new rules in their sorted position from the back of the list, so users can move some important rules to the top but still keep the rest of the list sorted.

**Comment by jayconrod** [comment]
> The other way I am thinking is to insert new rules in their sorted position from the back of the list, so users can move some important rules to the top but still keep the rest of the list sorted.

Different sections of a list could be split by blank lines. `gofmt` and `goimports` support that with imports in source files. I think `buildifier` has some support for that, too. It still seems a little complicated to me though. If there's a difference in meaning or importance of repository rules, it's already an option to put them in different macros.
