### ISSUE TITLE
Ignoring Go files consumed by handwritten go_library rules

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#699]
Although Gazelle does an excellent job of generating go_library rules, there are cases when we need to write them manually:

1. Go files generated by [gomock](https://github.com/jmhodges/bazel_gomock) should not be added to the `go_default_library`, as they are supposed to be used by tests only
2. Go files containing test utilities shared by internal and external tests. Due to https://github.com/bazelbuild/rules_go/issues/1877, internal and external tests need to be in separate go_test rules, so we have to create another go_library rule to build test utilities. This go_library rule is different than the `go_default_library`, as it is private to the current package.

The current approach of handling such use cases is to add an `gazelle:exclude` for those Go files we don't want to add to `go_default_library`. However, since those files are already consumed by hand-written `go_library`, Gazelle should be smart enough to exclude them from `go_default_library`.

@jayconrod Is there a case when people want a Go file to be built with two `go_library` rules at the same time?

**Comment by jayconrod** [comment]
In #697, I was worried about other rules, not necessarily `go_library`. I'm also kind of worried about rules generated by other extensions, though since #643, we exclude sources consumed by those. 

There are definitely cases where a source file may be consumed by multiple rules. Gazelle itself has generated `filegroups` that depend on source files also depended on by `go_library` rules. I'm not sure how common it is to have multiple `go_library` rules build the same source files, but I bet it happens occasionally.

For (1), it seems like `gomock` supports setting output file names. If the goal is to include them in `go_test` and not `go_library`, why not have the name end with `_test.go`?

For (2), I sympathize with this, but it it would be better to fix bazelbuild/rules_go#1877 than to add a workaround to Gazelle that affects all users. In any case, this problem affect a huge number of libraries: it happens when a package has both internal and external test archives, the external test imports the internal test, and another package imported by the external test imports the package being tested (instead of the internal test archive).

Are there other cases where this is needed can `# gazelle:exclude` is too annoying to use? Would another directive be better? It seems like some explicit user intent might be useful here.

Also, is this specific to sources consumed by `go_library`? In #697, it was sources depended on by any rule in the file.

**Comment by linzhp** [comment]
I am mainly concerning about `go_library` rules now. So I can update #697 to only exclude Go files consumed by manual `go_library` rules.

> For (1), it seems like gomock supports setting output file names. If the goal is to include them in go_test and not go_library, why not have the name end with _test.go?

We have a convention to put mock rules in the same build file as the mocked package, so it's easier to discover and reuse. Most of the references of mock rules are from other packages than the tests of the mocked packages. As a result, mocks have to be built in its own package instead of being included in a `go_test` rule.

I am actually curious about cases when a Go file would be needed to be built by two `go_library` rules. I agree in my case, we can add `gazelle:exclude` whenever we have a manually written `go_library` rule, but if #697 is merged, there would be no way for people to build a Go file from both manual `go_library` rule and `go_default_library`. If you think it as a valid use case, I don't mind abandoning #697.

**Comment by jayconrod** [comment]
> We have a convention to put mock rules in the same build file as the mocked package, so it's easier to discover and reuse. Most of the references of mock rules are from other packages than the tests of the mocked packages. As a result, mocks have to be built in its own package instead of being included in a go_test rule.

Are the mocked files in the same Go package (same package declaration and `importpath`)? Out of curiosity, how would you do this in a pure `go build` environment? Put separate build tags on the generated files I guess? Or build them as a separate package in a subdirectory?

Gazelle is meant to be very close to `go build` semantics, so any step away from that will cause problems. I realize supporting generated files at all are already a step away though.

> I am actually curious about cases when a Go file would be needed to be built by two go_library rules. I agree in my case, we can add gazelle:exclude whenever we have a manually written go_library rule, but if #697 is merged, there would be no way for people to build a Go file from both manual go_library rule and go_default_library. If you think it as a valid use case, I don't mind abandoning #697.

`nogo` does something similar to this, except we have duplicate `go_library` and `go_tool_library` rules with the same set of sources. I've also done this for Java programs before.

As a more general example, suppose you have a library with three parts: some generic files with interfaces and documentation, a "real" implementation, and a "fake" implementation. There are library rules for the real implementation (to be linked into binaries) and the fake implementation (to be linked into tests). Both libraries include the types and documentation.

You can probably express this with build tags, but the real implementation might also have a large number of `deps`, so it's sometimes simpler to have separate targets.

----

In any case, I don't think it's always clear whether source files (generated or not) should be included in multiple `go_libraries` or not. If you expect them to be included, it would be confusing when Gazelle deletes them from `go_default_library` because they're included somewhere else. There's no inverse of `# gazelle:exclude` to add them back in.

I think it's better to make an explicit choice with `# gazelle:exclude` instead. Alternatively, if the files are compiled as a separate package with a separate import path, putting them in a separate directory would better match conventions and expectations.

**Comment by linzhp** [comment]
> Are the mocked files in the same Go package (same package declaration and importpath)? Out of curiosity, how would you do this in a pure go build environment? Put separate build tags on the generated files I guess? Or build them as a separate package in a subdirectory?

Mock files are built as separate Go packages. By our convention, the mock package for `uber.com/foo/bar` would be something like `mock/uber.com/foo/bar`. Since we don't check in generated code, there is no physical directory corresponding to the mock import path. So we put the `gomock` rule and the go_library rule that builds the generated mock in the same BUILD.bazel file as the `uber.com/foo/bar:go_default_library`, ending up with multiple go_library rules per BUILD.bazel file.

To support `go build`, we have a Bazel aspect to collect all generated code location and import path, and developed a tool to copy them to `vendor`, which is set to ignored by Gazelle. We wish we can stop supporting `go build` one day, after we solve the IDE compatibility problems (debug, indexing generated code, etc).

> Gazelle is meant to be very close to go build semantics, so any step away from that will cause problems. I realize supporting generated files at all are already a step away though.

I think Gazelle and Bazel should support what `go build` supports. However, Bazel is more powerful than `go build`. Gazelle should not be limited by the capability of `go build`. Code generation rules produced by Gazelle is a great example. They allow us to generate Go code on the fly at build time, which is not possible with `go build`.

> I think it's better to make an explicit choice with # gazelle:exclude instead. Alternatively, if the files are compiled as a separate package with a separate import path, putting them in a separate directory would better match conventions and expectations.

Thanks for explaining. Let me close this issue then. I am happy to share how we build Go code at Uber if you have more questions.
