### ISSUE TITLE
go_repository should apply patches before executing gazelle

### ISSUE THREAD

**Issue by lazdmx** [bazelbuild/bazel-gazelle#735]
Problem appears if patch introduces new files and in that case new these files wouldn't be enlisted in generated build file.

**Comment by jayconrod** [comment]
#736 is a breaking change, so I can't accept it as-is.

In general, I'd recommend using `http_archive` or `git_repository` in a situation where a repository needs significant changes before build file generation. One of the patches applied can be build files generated by Gazelle. Dependencies declared by rules_go work this way, but that's mainly because they can't depend on Gazelle and can't use `go_repository`.

This could be implemented by adding additional attributes to `go_repository` for patches to be applied first. However, I'd rather not maintain that unless there's no other good way to solve the problem.

I'm not really clear on the issue you're seeing though. Please describe?

**Comment by lazdmx** [comment]
> I'm not really clear on the issue you're seeing though. Please describe?

The issue stems from the need to use https://github.com/blang/vfs with changes from https://github.com/blang/vfs/pull/22

> In general, I'd recommend using http_archive or git_repository in a situation where a repository needs significant changes before build file generation.

Agreed, but I ended up with patching gazelle itself through `http_archive`. Put it here just as  notice for someone who would look for all possible workarounds. 

> This could be implemented by adding additional attributes to go_repository for patches to be applied first. However, I'd rather not maintain that unless there's no other good way to solve the problem.

Sounds good. Also agreed that this problem should be investigated more carefully, but (IMHO) there are more chances that someone need to apply patch to repository **just before** build-file generation that **after**.

**Comment by jayconrod** [comment]
If you need to use a PR instead of the original upstream version of a repository, why not use the `replace` attribute in `go_repository`? That's the intended solution for this problem.

**Comment by lazdmx** [comment]
Didn't know about `replace` attribute, thanks for pointing this out I'll certainly check it. But even if it looks like a solution, I personally tends to use patches, since patches allow to hold more control over the code. I mean that forks by definitions is something that is less stable and that lives less than repo they originated from.

**Comment by jayconrod** [comment]
`replace` is meant to fill the same role as the `replace` directive in `go.mod`. It's good for short-term forks that only need exist while you're waiting for a PR to be merged upstream. `replace` has a problems though, so its use is lightly discouraged in the open source ecosystem. First, it's difficult to maintain a fork over a long period of time: you need to merge upstream changes and deal with conflicts. Second, downstream users of your repository can't use `replace` because it wouldn't be safe to apply `replace` when there are a large number of transitive dependencies with conflicting replacements. Because of these problems, it's better to get PRs merged quickly and avoid depending on forks long-term (or alternatively, do a hard fork, change the module path, and release separate versions).

Patches have the same problems, so I'd rather not include features that encourage their use if problems can be solved in a better way.

The one case where I've really wanted patches to be applied first is when a repository already has build files, but they don't work when the repository is used as an external dependency (e.g., they depend on a `vendor` directory or a Git submodule). That's pretty rare though, and `http_archive` with multiple patches seems like a good enough solution.
