### ISSUE TITLE
gazelle should have option to not filter files on build_tags

### ISSUE THREAD

**Issue by grahamjenson** [bazelbuild/bazel-gazelle#740]
### What version of gazelle are you using?

v0.20.0

### What version of rules_go are you using?

v0.22.1

### What version of Bazel are you using?

bazel 2.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

OSX

### What did you do?

Build two go_binaries that include `com_github_golang_protobuf` one built for WASM the other for local version.

### What did you expect to see?

Both of them to build.

### What did you see instead?

Errors because the incorrect version of a file is included.

Reference https://github.com/bazelbuild/rules_go/pull/2409

In a situation where a project has two versions of code that are mutually exclusive because of build tags (e.g. in protobuf library with `pointer_reflect.go` and `pointer_unsafe.go` ) gazelle will only ever include one file, there are no `build_tags` that can be selected to select both. 

If a project requires both version the only option is to import the library twice with `go_repository`. This is impossible with `rules_go` because it statically generates a patch from gazelle. 

Gazelle should have an option to not filter files based on build tags and just include them all, since the go_binary build will filter these files anyway.

**Comment by jayconrod** [comment]
My understanding of bazelbuild/rules_go#2409 was that some files were not being included because they used the `js` build tag. I'm not sure Gazelle or rules_go support `js` yet. They should.

For some additional background, Gazelle's approach when generating Go rules is to include files in a flat `srcs` list if they match any set of valid `GOOS` / `GOARCH` constraints (`js` and `wasm` may not yet be in that set of constraints). rules_go has its own tag filtering at build time. Platform-specific dependencies are split up using `select` expressions so that we don't attempt to fetch or build packages for the wrong platform. Gazelle can be configured to use a specific set of tags using the `-build_tags` flag or the `# gazelle:build_tags` directive.

**Comment by jayconrod** [comment]
Closing this issue.

Gazelle and rules_go both should work with wasm and js now. If not, please file a new issue.

I'd rather not add more options for dealing with build tags beyond `-build_tags` and `# gazelle:build_tags` which are already supported.
