### ISSUE TITLE
Confusion around getting go protobuf imports to work with bazel-gazelle

### ISSUE THREAD

**Issue by leeren** [bazelbuild/bazel-gazelle#746]
### What version of gazelle are you using?
0.20.0

### What version of rules_go are you using?
0.22.1

### What version of Bazel are you using?
2.2.0

### What did you do?
I am having a lot of trouble wrapping my head around how to get proto import declarations working with `go_proto_library` rules within go source files. I've found these three following issues to be relevant: [https://github.com/bazelbuild/bazel-gazelle/issues/305](url), [https://github.com/bazelbuild/bazel-gazelle/issues/209](url), [https://github.com/bazelbuild/rules_go/issues/1364](url) Unfortunately, despite going through them I can't seem to resolve my specific issue. 

I have the following very simple directory structure:
```
├── BUILD
├── fruit
│   ├── BUILD.bazel
│   └── fruit.proto
|   └── fruit.go
└── WORKSPACE
````

I made a test repo to look at if the following isn't clear enough, found [https://github.com/leeren/bazel-gazelle-help](here).

WORKSPACE:
```
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/leeren/bazel-gazelle-help
gazelle(name = "gazelle")
```

fruit.proto:
```
package fruit;

message Date {
  int32 month = 1;
  int32 day = 2;
}
```

fruit.go:
```
package fruit

import (
             "github.com/golang/protobuf/proto"
              pb "github.com/leeren/bazel-gazelle-help/fruit/fruit_go_proto" 
)

… 
```

Generated `BUILD` file:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "fruit_proto",
    srcs = ["fruit.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "fruit_go_proto",
    importpath = "github.com/leeren/bazel-gazelle-help/fruit",
    proto = ":fruit_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["fruit.go"],
    embed = [":fruit_go_proto"],
    importpath = "github.com/leeren/bazel-gazelle-help/fruit",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_protobuf//proto:go_default_library",
        "@com_github_leeren_bazel_gazelle_help//fruit/fruit_go_proto:go_default_library",
    ],
)
```
    
This is the output I get by running `bazel build //fruit:all`:

```
ERROR: /usr/local/google/home/leeren/test/fruit/BUILD.bazel:18:1: no such package '@com_github_leeren_bazel_gazelle_h
elp//fruit/fruit_go_proto': The repository '@com_github_leeren_bazel_gazelle_help' could not be resolved and referenc
ed by '//fruit:go_default_library'
ERROR: Analysis of target '//fruit:go_default_library' failed; build aborted: no such package '@com_github_leeren_baz
el_gazelle_help//fruit/fruit_go_proto': The repository '@com_github_leeren_bazel_gazelle_help' could not be resolved
INFO: Elapsed time: 0.124s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

This means that gazelle treated the import as an external source, correct? Which does not exist.

An alternative solution alluded to in the other referenced issues is to do the protobuf import relative to the workspace - that is, instead of `pb "github.com/leeren/bazel-gazelle-help/fruit/fruit_go_proto"`, `fruit/fruit.proto`, but that then gives me the error `gazelle: unrecognized import path "fruit/fruit.proto"` when running `gazelle`.

Thank you very much for the help!

**Comment by jayconrod** [comment]
There are a couple problems with this example.

* `fruit.proto` should have a line like `option go_package = "github.com/leeren/bazel-gazelle-help/fruit";`. This sets the `importpath` of the generated `go_proto_library`. Gazelle will try to guess an `importpath` if this isn't set, but it's better to be explicit.
* `fruit.go` should be in a separate directory unless it's intended to be compiled in the same package as the generated proto code (this is rare).
* `fruit.go` should import the generated proto package as `github.com/leeren/bazel-gazelle-help/fruit` instead of `github.com/leeren/bazel-gazelle-help/fruit_go_proto`. The `import` declaration has to match the `importpath`.

But Gazelle is also doing something weird here. It should print a warning and either resolve the unknown import to `//fruit/fruit_go_proto` or leave it out of `deps` entirely.

**Comment by jayconrod** [comment]
Also, could you confirm where this snippet is? It should be in `BUILD`, not `WORKSPACE`. If that `# gazelle:prefix` line is not found or doesn't match the import, that could explain the odd dependency resolution.

```
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/leeren/bazel-gazelle-help
gazelle(name = "gazelle")
```

**Comment by leeren** [comment]
Jay, thanks so much for getting back so quickly.

It was indeed the fact that I tried to get this work without the `option go_package` line being set that caused the issue. This indeed allowed my `BUILD` file to generate the correct `go_library` rule:

```
go_library(
  name = "go_default_library",
  srcs = ["fruit.go"],
    importpath = "github.com/leeren/bazel-gazelle-help/fruit",
    visibility = ["//visibility:public"],
    deps = [":fruity_go_proto"],
)
```
Since this is a best practice anyway, I'll just make sure to always use this!

**However, out of curiosity, how does Gazelle try to infer the `importpath` if it is not explicitly stated in the protobuf file, and a go source file tries to import the proto?** E.g. I noticed that if I don't include the `go_package` line in the go source file, and use `import pb "github.com/leeren/bazel-gazelle-help/example"`, the following rule is generated:

```
go_library(
    name = "go_default_library",
    srcs = ["fruit.go"],
    embed = [":fruit_go_proto"],
    importpath = "github.com/leeren/bazel-gazelle-help/fruit",
    visibility = ["//visibility:public"],
    deps = ["@com_github_leeren_bazel_gazelle_help//example:go_default_library"],
)
```

Is there ever a use-case for embedding protos into `go_library` rules?

Thank you so much!

**Comment by jayconrod** [comment]
> However, out of curiosity, how does Gazelle try to infer the importpath if it is not explicitly stated in the protobuf file, and a go source file tries to import the proto? E.g. I noticed that if I don't include the go_package line in the go source file, and use import pb "github.com/leeren/bazel-gazelle-help/example", the following rule is generated:

It will infer the import path by joining the current Go prefix (set with `# gazelle:prefix`) with the relative path from the prefix directory to the directory with the .proto. This works most of the time, but it will cause problems if there are multiple proto packages or Go packages in the same directory. If you're generating code for other languages, you'll have to add similar options, too; Go has conventions about this, but since they're not mandatory, it's better to be explicit.

> Is there ever a use-case for embedding protos into go_library rules?

Sometimes people do this to add extra methods to the generated proto types. It's rare though.

Code that reads and writes messages or acts as a gRPC client or server should be in a separate package though.
