### ISSUE TITLE
feature: support wire from google/go-cloud

### ISSUE THREAD

**Issue by ah-edg** [bazelbuild/bazel-gazelle#781]
https://blog.golang.org/wire documents how code generation is used to provide dependecy injection for Go.

The generator, [wire](https://github.com/google/wire), is used to build code for various backends of services that are supported by go-cloud. I am very unsure how to use or circumvent wire from Bazel and would like your support or guidance.

The alternatives I see are either selective import and usage of backend libraries and loss of the provided flexibility or importing everything and ending up with a gigantic binary.

We depend heavily on Bazel, especially rules_go and gazelle, and are super greatful for your continued excellent maintenance and support. Posting this issue does not feel right somehow, but it also does not quite fit Stackoverflow or rules_go or google/go-cloud. Still, here it is; maybe a solution comes cheap and with little effort. It might also help others.

**Comment by jayconrod** [comment]
I don't think Wire has a Bazel rule supporting it yet. Looks like google/wire#221 is the tracking issue for that. I think that would make sense to be implemented in the `wire` repo, since it would be coupled with the way `wire` works.

Once a rule exists, targets could be generated with a [Gazelle extension](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.rst). It probably also makes sense for that to live in the `wire` repo.

**Comment by ah-edg** [comment]
Thanks for clarifying. Somehow I missed it. If you don't want to use this for tracking, please feel free to close it.
