### ISSUE TITLE
How to structure test utilities in a directory?

### ISSUE THREAD

**Issue by quietgopher** [bazelbuild/bazel-gazelle#785]
### What version of gazelle are you using?
v0.20.0

### What version of rules_go are you using?
v0.21.3

### What version of Bazel are you using?
2.1.0

### Does this issue reproduce with the latest releases of all the above?
It's kinda separate from a version issue.

### What operating system and processor architecture are you using?
mac v10.15.2

### What did you do?

I'm trying to figure out the best practice for how gazelle supports test utilities (e.g. separate functions).  I have some functions that create test objects that I want to share between tests.  I could always put these into one of the test files but that seems kinda sloppy and hard to find.  I could always postfix with "_test.go" but that seems hacky.

### What did you expect to see?
I looked through the docs but I didn't see an easy way to do this.

### What did you see instead?
I could try gazelle:exclude and avoid gazelle.  I would hope there would be a way to support this in gazelle.

My structure is pretty basic.  If I call the util "testutils.go", it gets included in the go_default_library (which I don't want).

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        ...non test files go files.  I'd like to exclude testutils.go
    ],
    # importpath = ...
    visibility = ["//visibility:public"],
    # deps = [...],
)

go_test(
    name = "go_default_test",
    srcs = [ ... test files ]
    embed = [":go_default_library"],
    deps = [ ... ]
)

```

**Comment by jayconrod** [comment]
Are the test utilities just used by tests in a single package? Or are they shared by multiple packages?

If the utilities are used by a single package, use the suffix `_test.go`. The file doesn't have to actually declare test functions. This will make Gazelle include the files in the `srcs` attribute of `go_test`. It sounds like they should be compiled together with the test instead of the library being tested.

If the utilities are used by multiple packages, put them in a separate directory and don't use the suffix `_test.go`. They should be built as a `go_library` that may be imported by tests. You may want to manually add the `testonly = True` attribute to this library to ensure it can only be depended on by tests and their dependencies.

**Comment by quietgopher** [comment]
Just in the same package.  I was guessing there'd be a cleaner way.  I'll
keep with suffix _test.go.

Thanks!

**Comment by jayconrod** [comment]
Sure, glad to help!
