### ISSUE TITLE
[Feature] Add retry places when GOPROXY is needed

### ISSUE THREAD

**Issue by xytan0056** [bazelbuild/bazel-gazelle#789]
### What version of gazelle are you using?

2078a44d2bba287db98b2b48b5f6cf4f08642489

### What version of rules_go are you using?

9794aacb240809111dfb9d587d40475b2819310e

### What version of Bazel are you using?

3.0.0

There are multiple places where GOPROXY is used to fetch module information
https://github.com/bazelbuild/bazel-gazelle/blob/master/cmd/fetch_repo/module.go#L77
https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/modules.go#L150
https://github.com/bazelbuild/bazel-gazelle/blob/master/repo/remote.go#L419
In an event where GOPROXY is not stable enough to provide 100% availability (especially considering an organization can maintain its own proxy to serve internal modules), `go_repository` would fail on a single try of these commands and cause the entire build to fail. Can we add an option to retry in this scenario? 
This could be done in go [28194](https://github.com/golang/go/issues/28194), but likely won't happen soon.

**Comment by jayconrod** [comment]
I'd rather not add this to Gazelle or fetch_repo. golang/go#28194 would be the place to implement it, though I'm skeptical it should be there either. Retries add complication, and if they're done poorly, they can add load to an already overloaded system.

It's possible to workaround this already with a local `GOPROXY` service that does retries.

**Comment by wade-arista** [comment]
@jayconrod would you consider this to be an acceptable extension to fetch_repo if it were configurable, something like:

```python
go_deps.config(
    fetch_repo_retries=4,
)
```

**Comment by jayconrod** [comment]
Retries should be implemented in `go mod download` itself, not here. The upstream issue is https://github.com/golang/go/issues/28194, which has been open for... quite a while. If you're interested in working on that, discuss the approach on the issue first. A previous attempt to fix it stalled because that discussion didn't happen. There are some considerations around when to retry HTTP fetches, Git fetches, timeouts, expontential backoff, and so on.

You can workaround this with a local proxy service, or by setting `GOPROXY=https://proxy.golang.org|https://proxy.golang.org|https://proxy.golang.org,direct` (repeating the same proxy, separated by `|` rather than `,`).

**Comment by wade-arista** [comment]
Thanks, yeah, understood. I just thought I'd check in case. I'm doing the same in a `single_version_override`, instead. Our use case isn't conducive, at the moment, to either running a separate local proxy everywhere we invoke bazel, nor to waiting a long time for a patch to come through `go mod download`, but eventually that might be way to remove the override.
