### ISSUE TITLE
Generate external dependency resolve cache with update-repos

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel-gazelle#851]
> When Gazelle resolves an import path to an external dependency, it attempts to discover the remote repository root over HTTP. Gazelle skips this discovery step for a few well-known domains with predictable structure, like golang.org and github.com.

Resolve external dependency could be flaky/slow when there are network access restrictions. It would be nice to have that information cached when calling `update-repos`.

For instance, gazelle produces the following debug messages when fetching `go_repository`:

> DEBUG: /<redacted>/external/bazel_gazelle/internal/go_repository.bzl:186:18: com_github_yuin_goldmark: gazelle: finding module path for import gopkg.in/russross/blackfriday.v2: exit status 1: go: finding module for package gopkg.in/russross/blackfriday.v2
go: downloading gopkg.in/russross/blackfriday.v2 v2.0.1
can't load package: package gopkg.in/russross/blackfriday.v2: gopkg.in/russross/blackfriday.v2@v2.0.1: verifying module: gopkg.in/russross/blackfriday.v2@v2.0.1: Get "https://sum.golang.org/lookup/gopkg.in/russross/blackfriday.v2@v2.0.1": Server UnReachable

**Comment by jayconrod** [comment]
`update-repos` will use `go mod download` or something similar to look up most information. That should store information in the module cache in your home directory, and it can be configured with these [environment variables](https://golang.org/ref/mod#environment-variables).

For this error in particular, it looks like `sum.golang.org` is not reachable. If that's expected, you can set it to `GOSUMDB=sum.golang.google.cn` (mirror for mainland China) or disable it entirely with `GOSUMDB=off` (this will not authenticate new modules; use with caution).

**Comment by ashi009** [comment]
It's definitely an option for most of the configurations. 

However, we really want it to work in offline mode, say air-gapped CI environment -- which only has access to the repo cache in the same network.

The error message above was due to the fact that gazelle needs to generate build files for the go files from the repo cache.

**Comment by jayconrod** [comment]
> The error message above was due to the fact that gazelle needs to generate build files for the go files from the repo cache.

Hmm, when I first read this, I thought the error was coming from `fetch_repo`, but you're right, this is coming from Gazelle's external dependency resolution. When invoked by `go_repository`, Gazelle does use the same module cache as `fetch_repo`, but since there's no `go.sum`, by default it's going to use the checksum database to verify downloads.

#499 is relevant: there's a strong argument for Gazelle not accessing the network when invoked by `go_repository`.

> However, we really want it to work in offline mode, say air-gapped CI environment -- which only has access to the repo cache in the same network.

The best way to do that is to set `GOPROXY`, `GOPRIVATE`, and other environment variables, the same as you would with `go build` or `go test`. You may want to stand up a closed proxy server in the CI environment for this purpose, or point to a read-only module cache with a `file://` URL. Vendoring might also be an option.

When `go_repository` is invoked with `urls` (HTTP mode) or `commit` (Git mode), Gazelle actually has different semantics than when it's invoked with `version` (module mode): It acts like it's in `GOPATH` mode. Because `GOPATH` is close to being deprecated, I'd rather not add more support for it. It would be better to focus on improving `go_repository` in module mode. If it makes sense to disable network access for Gazelle in `go_repository` (#499), I think we should do that instead.

**Comment by ashi009** [comment]
SGTM. #499 sounds right, closing this.
