### ISSUE TITLE
Very slow fetch of buildtools

### ISSUE THREAD

**Issue by napei** [bazelbuild/bazel-gazelle#874]
### What version of gazelle are you using?

0.21.1

### What version of rules_go are you using?

0.23.8

### What version of Bazel are you using?

3.3.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Windows 10 Pro - AMD 64-bit

### What did you do?

 - Following the startup example workspace etc. Nothing different
 - Run `bazel run //:gazelle`

### What did you expect to see?

A quick-ish execution 

### What did you see instead?

```
Analyzing: target //:gazelle (20 packages loaded, 188 targets configured)
    Fetching @com_github_bazelbuild_buildtools; fetching 915s
```

`Ctrl+C` and re-running yields the same wait, but with a dramatic increase in targets.

```
Analyzing: target //:gazelle (55 packages loaded, 7103 targets configured)
    Fetching @com_github_bazelbuild_buildtools; fetching 32s
```

Very very new to bazel (first time), and I had this working before, until random `permission denied` errors with internal go deps and ended up deleteing it all and starting again. It's done this every single time now, and it's kida alittle frustrating.

Task manager just says 0.1MB/s disk usage, and no network traffic so not exactly sure what it's doing, and why it's so slow. Most of the time 1000+ seconds.

**Comment by napei** [comment]
So I bit the bullet and I'm now giving WSL2 a go in terms of running my dev environment through it and no issues so far at all. It seems to be a windows issue.

**Comment by jayconrod** [comment]
Bazel on Windows is generally a lot slower than on other platforms because NTFS performance with lots of small files is pretty bad (operations that take hundreds of microseconds on Linux take milliseconds on Windows with the same hardware). Bazel also has to copy files instead of symbolic linking them, since symbolic links aren't usually available to non-admin users. So I wouldn't be surprised to see a fresh build of Gazelle take a minute or two. Antivirus can also slow that down by a factor of 20x. So my guess is that this is a local system issue.

Is there any reason to believe this is a bug? Unless there's a specific problem I can help with, there's not much I can do.

**Comment by napei** [comment]
@jayconrod Thanks for the info. I don't think it's a bug, it was present in all versions I tried. Given WSL2 works perfectly I'll say it's a windows thing.

There were plenty of other `(Permission denied)` errors which after looking around is about deleting folders and such on Windows. I think it's a windows problem in general.

After spinning up WSL2 and getting that working well, I managed to merge 4 backend repos into a monorepo, set up build tools and container deployment, and CI integration all within a few hours. So I think Linux is the way to go :smile:
