### ISSUE TITLE
Build failure when run in kubernetes-sig/controller-tools

### ISSUE THREAD

**Issue by ob** [bazelbuild/bazel-gazelle#924]
I was trying to build [kubernetes-sigs/controller-tools](https://github.com/kubernetes-sigs/controller-tools) using bazel 3.5.0, and followed the instructions on the main README from Gazelle.

### What version of gazelle are you using?

0.22.1

### What version of rules_go are you using?

0.24.3

### What version of Bazel are you using?

3.5.0

### Does this issue reproduce with the latest releases of all the above?

Yeah.

### What operating system and processor architecture are you using?

```
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
```

### What did you do?

```
$ git clone git@github.com:kubernetes-sigs/controller-tools.git
$ cd controller-tools
```

Create `WORKSPACE` and `BUILD.bazel` files as per the main README.

```
$ bazel run //:gazelle
$ bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=deps.bzl%go_dependencies
$ bazel build //cmd/...
INFO: Invocation ID: 901741d9-c8be-4b47-87ed-ea9ab7200bcc
ERROR: /Users/obonilla/tmp/controller-tools/cmd/controller-gen/BUILD.bazel:3:11: no such package '@io_k8s_sigs_controller_tools//pkg/crd': The repository '@io_k8s_sigs_controller_tools' could not be resolved and referenced by '//cmd/controller-gen:controller-gen_lib'
ERROR: /Users/obonilla/tmp/controller-tools/cmd/controller-gen/BUILD.bazel:3:11: no such package '@io_k8s_sigs_controller_tools//pkg/genall/help': The repository '@io_k8s_sigs_controller_tools' could not be resolved and referenced by '//cmd/controller-gen:controller-gen_lib'
ERROR: Analysis of target '//cmd/controller-gen:controller-gen_lib' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.149s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
```

### What did you expect to see?

A successful build.

### What did you see instead?

```
ERROR: /Users/obonilla/tmp/controller-tools/cmd/controller-gen/BUILD.bazel:3:11: no such package '@io_k8s_sigs_controller_tools//pkg/genall/help': The repository '@io_k8s_sigs_controller_tools' could not be resolved and referenced by '//cmd/controller-gen:controller-gen_lib'
```

**Comment by jayconrod** [comment]
What did you write for the `# gazelle:prefix` directive in `BUILD.bazel`? It should be:

```
# gazelle:prefix sigs.k8s.io/controller-tools
```

The prefix should match the module path in `go.mod`. I guess the Go extension should probably be changed to read a prefix from `go.mod` automatically so that would no longer be necessary.

Also, try running `bazel run //:gazelle` again after `update-repos`. The `update-repos` command can affect the output of a normal run of Gazelle. The README should be updated to fix that.

After that, I see an error like:

```
ERROR: /private/var/tmp/_bazel_jayconrod/b32a2121ffa75e02622b4c8a64487730/external/io_k8s_apimachinery/pkg/apis/meta/v1/BUILD.bazel:15:17: no such package '@io_k8s_apimachinery//k8s.io/apimachinery/pkg/runtime': BUILD file not found in directory 'k8s.io/apimachinery/pkg/runtime' of external repository @io_k8s_apimachinery. Add a BUILD file to a directory to mark it as a package. and referenced by '@io_k8s_apimachinery//pkg/apis/meta/v1:v1_go_proto'
```

This happens because Kubernetes uses proto import paths that don't match the module root directory. There are ways to adjust the import prefix in `go_repository`, but it's probably better to disable proto rule generation entirely. You can do that by running `update-repos` with `-build_file_proto_mode=disable_global`. This will add `build_file_proto_mode = "disable_global"` to imported `go_repository` rules. You'll also need to add `# gazelle:proto disable_global` to your root build file.

**Comment by ob** [comment]
Thanks, I think I've made it work by disabling proto mode like you suggested.
