### ISSUE TITLE
language/go: wrong visibility for module path ending with "internal"

### ISSUE THREAD

**Issue by douglas-plezentek** [bazelbuild/bazel-gazelle#960]
### What version of gazelle are you using?
v0.22.2:
```
http_archive(
    name = "bazel_gazelle",
    sha256 = "b85f48fa105c4403326e9525ad2b2cc437babaa6e15a3fc0b1dbab0ab064bc7c",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
    ],
)
```

### What version of rules_go are you using?
v0.24.5
```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "d1ffd055969c8f8d431e2d439813e42326961d0942bdf734d2c95dc30c369566",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.5/rules_go-v0.24.5.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.5/rules_go-v0.24.5.tar.gz",
    ],
)
```

### What version of Bazel are you using?
```
Bazelisk version: v1.7.4
Build label: 3.7.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 24 17:38:30 2020 (1606239510)
Build timestamp: 1606239510
Build timestamp as int: 1606239510
```
### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Linux Debian Buster amd64
```go.mod
module <SOME_MODULE>

go 1.13

require (
    golang.org/x/net v0.0.0-20201110031124-69a78807bb2b // indirect
    modernc.org/ccgo v1.0.0 // indirect
    modernc.org/ccir v1.0.0 // indirect
    modernc.org/internal v1.0.0 // indirect
    modernc.org/memory v1.0.4 // indirect
    modernc.org/sqlite v1.0.0
)
```

```main.go
package main

import (
    "database/sql"
    "fmt"

    _ "modernc.org/sqlite"
)

func main() {
    fmt.Println("Opening in-memory sqlite database")
    db, err := sql.Open("sqlite", ":memory:")
    if err != nil {
        fmt.Println(err)
        return
    }

    if _, err = db.Exec(`
DROP TABLE IF EXISTS sqlite;
CREATE TABLE sqlite(i);
    `); err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println("Done")
} 
```

```BUILD.bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix <SOME_MODULE>
gazelle(name = "gazelle")

go_library(
    name = "sqlite_lib",
    srcs = ["main.go"],
    importpath = "<SOME_MODULE>",
    visibility = ["//visibility:private"],
    deps = ["@org_modernc_sqlite//:sqlite"],
)

go_binary(
    name = "sqlite",
    embed = [":sqlite_lib"],
    visibility = ["//visibility:public"],
)
```

### What did you do?
I created a proof-of-concept repo that tries to import modernc.org/sqlite v1.0.0

### What did you expect to see?
I expected it to build, since go build works

### What did you see instead?
```
ERROR: /home/douglas/.cache/bazel/_bazel_douglas/cea54a25b012f5a3480c4aba3dcd4d3f/external/org_modernc_ccgo/crt/BUILD.bazel:3:11: in go_library rule @org_modernc_ccgo//crt:crt: target '@org_modernc_internal//buffer:buffer' is not visible from target '@org_modernc_ccgo//crt:crt'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//vanilla/sqlite:sqlite' failed; build aborted: Analysis of target '@org_modernc_ccgo//crt:crt' failed
INFO: Elapsed time: 2.927s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 362 targets configured)
FAILED: Build did NOT complete successfully (13 packages loaded, 362 targets configured)
```

**Comment by robfig** [comment]
I suppose that the visibility calculation does not handle the possibility of being cross-module.  Here's a reproducer

1. Clone https://github.com/robfig/gazelle-repro
2. Run `bazel build :sqlite` 

Taking a look

**Comment by robfig** [comment]
Related:
https://github.com/bazelbuild/bazel-gazelle/issues/619

**Comment by robfig** [comment]
I was thinking of using public visibility for modules that are named "internal", since it seemed impossible to know exactly which other modules might depend upon them. But maybe that's not the intended direction. Happy to help given some guidance, @jayconrod

**Comment by jayconrod** [comment]
Sorry for not triaging this earlier. Must have missed it when it was opened. @robfig thanks for the minimal repro. This does indeed look like a bug.

There's some code intended to handle cases like this in [language/go.generator.commonVisibility](https://github.com/bazelbuild/bazel-gazelle/blob/6530ffd5f1f313fdc1df7af3f63f954772789f04/language/go/generate.go#L703). That was intended to fix a bug in the GCP client libraries where a nested module referenced internal packages in a parent module.

It doesn't look like that fix handles this case, but the idea could be extended here. We have a list of all modules we might care about (populated by reading a configuration file generated from `go_repository` declarations in `WORKSPACE`). We could use that to figure out what modules to extend visibility to.

**Comment by robfig** [comment]
Looking at adding a test in integration_test.go and ran into a few questions -- 

(a) the identical setup would run Gazelle via a repository_rule and verify that it sets visibility properly, but I wasn't sure how to arrange for that to happen, without adding a local path attribute. Any idea if that's possible today?

(b) assuming it's not necessary to accomplish (a) to make it a good test, I was then wondering how exactly Gazelle is invoked by repository_rules,  assuming that it is provided a path to the configuration file generated from `go_repository` declarations that you mentioned. I suppose `--subcommands [-s]` only works on build rules, because that didn't do the trick. Any idea how to print that for diagnosing in the future? 

(c) is the configuration you're referring to the `updateConfig.repos` ? I was under the impression that it being populated by the universe of repositories was an optimization, but not guaranteed. For example, I recently sped it up for us by pointing Gazelle to the generated bzl with `go_repository` rules. Assuming that's how `repos` is populated, is it ok to require `repos` to be comprehensive for the visibility calculation to work? I wasn't sure we'd want to rely on that, but perhaps it's ok.

Thanks for your advice

**Comment by jayconrod** [comment]
> (a) the identical setup would run Gazelle via a repository_rule and verify that it sets visibility properly, but I wasn't sure how to arrange for that to happen, without adding a local path attribute. Any idea if that's possible today?

`go_repository` invokes Gazelle with the `-repo_config` flag, pointing to a file generated by `//cmd/generate_repo_config`. The syntax is basically the same as `WORKSPACE`, but only the `name` and `importpath` attributes of `go_repository` need to be included.

If it turns out it really is necessary to run `go_repository` in a test (probably not for this), new cases can be added in `internal/go_repository_test.go`.

> (b) assuming it's not necessary to accomplish (a) to make it a good test, I was then wondering how exactly Gazelle is invoked by repository_rules, assuming that it is provided a path to the configuration file generated from go_repository declarations that you mentioned. I suppose --subcommands [-s] only works on build rules, because that didn't do the trick. Any idea how to print that for diagnosing in the future?

I don't know of a way to get Bazel to print commands run by repository rules. I usually end up adding `print` calls to debug them.

For the details of generating the config file, see `internal/go_repository_config.bzl` and `//cmd/generate_repo_config`. For invoking Gazelle, `internal/go_repository.bzl`.

> (c) is the configuration you're referring to the updateConfig.repos ? I was under the impression that it being populated by the universe of repositories was an optimization, but not guaranteed. For example, I recently sped it up for us by pointing Gazelle to our generated bzl that had the go_repository rules. Assuming that's how repos is populated, is it ok to require repos to be comprehensive for the visibility calculation to work? I wasn't sure we'd want to rely on that, but perhaps it's ok.

The list of repos ends up going into `config.Config.Repos`, so it's available to every extension.

I think it's a really good question whether `go_repository` should require a complete configuration file. I think it probably should: looking up modules on the network is slow and error-prone, and the same lookup may need to be repeated across multiple `go_repository` rules.

However, changing that may break builds without an obvious way to fix them. So it needs to be done carefully, maybe with a new `go_module` rule that works differently. It might also be a chance to create a general purpose `gazelle_repository` rule that works with other languages.

I've been pointing to #499 as the issue to at least cover a "strict mode" which wouldn't go out to the network.
