### ISSUE TITLE
go_repository: support setting environment variables like GOPROXY

### ISSUE THREAD

**Issue by dirkboye** [bazelbuild/bazel-gazelle#966]
We are mirroring all our dependency to our company's local network and also use an on-premise
GOPROXY implementation.

We can enable GOPROXY by

1. setting a host environment variable before running any bazel command
2. setting --repo_env in .bazelrc

The problem we have with 1: our users should not have to change their host's environment to use our goproxy. If our users have a misconfigured environment they will start accessing remote locations (which they can't/shouldn't)

The problem with solution 2: --repo_env does not work with `bazel query` commands and our CI depends on those commands and running bazel query alternating with bazel build/run  the analysis cache is discarded every time with message

INFO: Build option --repo_env has changed, discarding analysis cache.

The current workaround is a patch that we apply when importing gazelle into our WORKSPACE.

The patch looks like this:
```
diff -urN b/deps.bzl c/deps.bzl
--- b/deps.bzl
+++ c/deps.bzl
@@ -38,11 +38,13 @@
 
 def gazelle_dependencies(
         go_sdk = "",
-        go_repository_default_config = "@//:WORKSPACE"):
+        go_repository_default_config = "@//:WORKSPACE",
+       go_proxy = ""):
     if go_sdk:
         go_repository_cache(
             name = "bazel_gazelle_go_repository_cache",
             go_sdk_name = go_sdk,
+           go_proxy = go_proxy,
         )
     else:
         go_sdk_info = {}
@@ -60,6 +62,7 @@
         go_repository_cache(
             name = "bazel_gazelle_go_repository_cache",
             go_sdk_info = go_sdk_info,
+           go_proxy = go_proxy,
         )
 
     go_repository_tools(
diff -urN b/internal/go_repository_cache.bzl c/internal/go_repository_cache.bzl
--- b/internal/go_repository_cache.bzl
+++ c/internal/go_repository_cache.bzl
@@ -64,6 +64,11 @@
         gopath = go_path,
         gocache = go_cache,
     )
+    if ctx.attr.go_proxy:
+       env_content += """
+GOPROXY='{goproxy}'
+""".format(goproxy = ctx.attr.go_proxy)
+
     ctx.file("go.env", env_content)
     ctx.file("BUILD.bazel", 'exports_files(["go.env"])')
 
@@ -72,6 +77,7 @@
     attrs = {
         "go_sdk_name": attr.string(),
         "go_sdk_info": attr.string_dict(),
+       "go_proxy": attr.string(),
     },
     # Don't put anything in environ. If we switch between the host cache
     # and Bazel's cache, it shouldn't actually invalidate Bazel's cache.
```

Using this patch it is possible to define a go_proxy as an argument to `gazelle_dependencies`.
This go_proxy will still be overridden by a env variavle GOPROXY from host or --repo_env.

Is this a solution worthwhile to create a pull request from?

**Comment by jayconrod** [comment]
I think setting environment variables before running commands (solution 1) should be the best practice in general. `gazelle` and `fetch_repo` should use the same settings as `go` commands run by the users for the most part. Note that you can set those permanently using `go env -w`.

That said, I think it's reasonable to have project-specific settings for environment variables, and there's no way to do that with the `go` command at the moment. Setting `go_proxy` specifically seems too limiting, since one might wish to set other things like `GOPRIVATE`. So perhaps `gazelle_dependencies` should accept an optional `go_env` parameter, which would be a `dict` mapping environment variable names to values? That could be written to `@bazel_gazelle_go_repository_cache//:go.env`, which is already used for a few other things.

**Comment by dirkboye** [comment]
Thanks for your reply. An optional `go_env` parameter sounds good! I'll prepare a pull request.
