### ISSUE TITLE
Gazelle generates library-level visibility instead of package-level.

### ISSUE THREAD

**Issue by mkilpatrick** [bazelbuild/bazel-gazelle#985]
### What version of gazelle are you using?
A forked version that is close to up to date:
https://github.com/yext/bazel-gazelle
50712ce78b4843fc8620278075383e1ca53dfd74

### What version of rules_go are you using?
0.24.10

### What version of Bazel are you using?
3.5.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
OSX/x86

### What did you do?
Running Gazelle on a Go path results in the go_library with `visibility = ["//visibility:public"],`.

### What did you expect to see?
It's my understanding that package level visibility is preferred and only library visibility should be set if it's overriding the package level visibility.

Additionally, should it default to the current package, rather than making it public?

### What did you see instead?
The visibility is set at the library level.

**Comment by achew22** [comment]
Can you provide a link to a repo that this can be run in, as well as a full BUILD file both as it was generated and as you believe it should be?

**Comment by jayconrod** [comment]
Not sure I understand this issue? Do you mean Go packages (compiled libraries) or Bazel packages (corresponding to a build file)? I'm assuming Bazel packages.

By default, package visibility is `//visibility:private`. That can be overridden in a [`package`](https://docs.bazel.build/versions/master/be/functions.html#package) declaration by setting `default_visibility`. Gazelle should respect those declarations if they're there and will not add or update `visibility` attributes.

If package-level visibility declarations are not present, Gazelle generates `visibility` attributes for each `go_library` and `go_binary` target, matching what the `go` command would do.

**Comment by mkilpatrick** [comment]
Steps to reproduce:
```
$ git clone git@github.com:mkilpatrick/gazelle_repro.git
$ cd gazelle_repro
$ bazel run :gazelle
```

You'll notice that the BUILD.bazel file generated in /foo looks like
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "foo",
    srcs = ["foo.go"],
    importpath = "github.com/mkilpatrick/gazelle_repro/foo",
    visibility = ["//visibility:public"],
)
```

Maybe this is undesired, but would it be possible for it to instead generate less permissively and at the package level?
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//foo:__subpackages__"])

go_library(
    name = "foo",
    srcs = ["foo.go"],
    importpath = "github.com/mkilpatrick/gazelle_repro/foo",
)
```

**Comment by jayconrod** [comment]
Sorry to take so long to get back to this.

Gazelle's charter (for Go at least) is to map the semantics of the `go` command to Bazel build files as closely as possible. There are a few knobs for customization, but we try to avoid them if possible since they make Gazelle more complicated to use (and to maintain).

Gazelle sets the `go_library` `visibility` attribute based on its `importpath`. If there is an `internal` path element somewhere, the package should be visible to the same set of packages it would be visible to following the `go` command's rules. For example, `example.com/foo/internal/bar` should be visible to `example.com/foo/...`.

You can override that by adding a `package` declaration with `default_visibility` in each build file. When that's present, Gazelle won't add `visibility` attributes to targets it generates or updates. You may need to remove existing `visibility` attributes.

If you need to do this for a lot of packages, [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) is a great tool for making bulk edits to build files.
