### ISSUE TITLE
Add ability to keep custom binary names

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel-gazelle#99]
Because of https://github.com/bazelbuild/rules_go/issues/1239, I'm trying to find a way to get my previously-working build to work again. The problem is that I have a bunch of tools (not tests!) that depend on `go_binary` targets as data and need to find the binaries to use them. I also have user-facing instructions that tell people to run `./bazel-bin/foo/bar`, which don't work any more and cannot be written in a generic manner due to the unpredictable platform-specific component.

For the most part, I got a workaround by using a `genrule` that just copies the binary to the expected location, thus eliminating the platform-specific part of the path. These look like:

```python
def stage_go_binary(name, src, visibility=None):
  native.genrule(
      name = "stage-%s" % name,
      srcs = [src],
      outs = [name],
      cmd = "cp $(location %s) $@" % src,
      output_to_bindir = 1,
      visibility = visibility,
  )

def staged_go_binary(name, visibility=None, **kwargs):
  go_binary(
      name = "%s-bin" % name,
      **kwargs
  )
  stage_go_binary(
      name = name,
      src = ":%s-bin" % name,
      visibility = visibility,
  )
```

so that, instead of calling `go_binary` from my build files I call `staged_go_binary` that does the magic thing in the background. However, as you can imagine this confuses Gazelle as it does not know that `staged_go_binary` is equivalent to `go_binary` and thus Gazelle reverts all my changes. Fine.

So I went with the simpler alternative of not replacing the binary targets, but instead doing this:

```python
go_binary(
    name = "foo-bin",
    ...
)

stage_go_binary(
    name = "foo",
    src = ":foo-bin",
)
```

in the hopes that this extra amount of manual work would keep Gazelle happy... but it doesn't either because Gazelle cannot recognize that my `foo-bin` is really the `foo` it wants to generate.

All these hacks are awful, but I don't see other solutions based on the original issue quoted above. Therefore, I was wondering if Gazelle could be extended to have an extra tag to tell it that a specific target was renamed. E.g.:

```python
go_binary(
    name = "foo-bin",  # gazelle:name foo
    ...
)
```

This feels like a feature that would be useful in other situations as well. Thoughts?

**Comment by jayconrod** [comment]
This seems like a good temporary measure, but I'm worried it will interfere with some planned changes.

In the future, I'd like Gazelle's matching logic to be more flexible. The matching logic finds existing rules that correspond with generated rules so they can be merged. Currently, we just match using name and kind. I think at least two improvements need to be made here:

* There should be more flexibility in naming, especially for `go_binary` rules. In general, if there's one binary rule in a directory, we should probably match that. There's some risk here that we could end up deleting manually written rules.
* There should be a way to specify a kind is an alias for another kind. For example, instead of updating a `go_binary` rule, Gazelle should update a `go_image` rule.

There may be cases (like this) where we use directives to give users control over the rule matching. This probably needs to be done in a way that will continue working if Gazelle's naming scheme changes (we want to get rid of "go_default_library" and support multiple packages in the future). So rather than giving a rule a different name, we may want to say something like "this rule should match the `go_library` rule for package X".

**Comment by jmmv** [comment]
Yeah, better automatic matching that respects what appear to be manual edits (like a name difference) would be much better than tagging. But maybe a tag can be added in the interim? Seems simple, and when you have better matching, you'd just start ignoring the comment.

Just a thought. I guess I'll have to end up something pretty ugly for now anyway...
